### ISSUE TITLE
KDTree time issue

### ISSUE THREAD

**Issue by nkanderson00** [UPBGE/upbge#922] opened 2018-11-05 01:01 UTC
A very strange issue I found when using KDTree. Every 7 iterations of `kd.find_range()` , it takes 5 times as long to perform. See the attached image.

I have the code print the time it takes to run `kd.find_range()`. As you can see, every 7 iterations, it takes 0.05 seconds rather than the usual 0.01 seconds.

![image](https://user-images.githubusercontent.com/28845130/47972645-219fa300-e06c-11e8-8d9d-f2fab1121cb0.png)

**Comment by nanderson00** [comment] 2018-11-05 01:15
after more testing, I have found it happens every 6th, 7th, or 8th time the function is run.  It also happens every random 6, 7, or 8 iterations.

**Comment by lordloki** [comment] 2020-12-22 00:08
The issue in current 0.2.5a is reduced to 2 times only.
![image](https://user-images.githubusercontent.com/1015605/102833675-0467f300-43f2-11eb-94b2-a93e634279b6.png)

I close this report as this function belong to BF and we try to avoid modify its code if the issue is not very big.

Thanks for reporting.

**Closed by lordloki** 2020-12-22 00:08 UTC
