### ISSUE TITLE
UPGE crashing if you add a game property, game component or game object under Game object properties and use ctrl Z to undo

### ISSUE THREAD

**Issue by ItsCubeTime** [UPBGE/upbge#1554] opened 2021-09-16 09:06 UTC
https://user-images.githubusercontent.com/20190653/133584118-e75a3219-2bae-44bc-b1fb-e31dadb45eb6.mp4

![image](https://user-images.githubusercontent.com/20190653/133584213-2ce13f5c-bce2-4d28-9594-1c0d038badbb.png)

**Comment by ItsCubeTime** [comment] 2021-09-16 09:12
Likely related to: https://developer.blender.org/T91294

**Comment by youle31** [comment] 2021-09-16 09:23
Yes, I just tested applying the patch I propose here: https://developer.blender.org/T91294 and it prevents the crash too in upbge when adding a game property then undo (we are using the full old undo version in upbge because new undo was causing issues at game exit).

For now, upbge master is a bit unstable so better to keep a version from september beginning.

**Comment by youle31** [comment] 2021-09-16 09:24
I close this report as it sounds a duplicate of https://github.com/UPBGE/upbge/issues/1555

**Closed by youle31** 2021-09-16 09:24 UTC
