### ISSUE TITLE
UPBGE .33 27/7/2022 will be closed after removing nodes in logic brick node view (Bricky Nodes addon)

### ISSUE THREAD

**Issue by BlackEagle1983** [UPBGE/upbge#1718] opened 2022-07-24 12:32 UTC
Hello . when I delete a node in logic brick node view UPBGE .33 will be closed without any error message . 

windows 10 pro
cpu i5 4690
ram 12
graphic GTX 950 2 gig

**Comment by youle31** [comment] 2022-07-25 08:26
Video shared by report author:
[1.zip](https://github.com/UPBGE/upbge/files/9179360/1.zip)

Thanks for report, i'll investigate later on it

**Comment by youle31** [comment] 2022-07-26 06:56
I can't reproduce the issue in last upbge master (last upbge builded from sources)

Could you:

1. Share a test file
2. Wait for next build and test again AND if it doesn't crash anymore, close this report

Thanks

**Comment by BlackEagle1983** [comment] 2022-07-26 08:37
> I can't reproduce the issue in last upbge master (last upbge builded from sources)
> 
> Could you:
> 
> 1. Share a test file
> 2. Wait for next build and test again AND if it doesn't crash anymore, close this report
> 
> Thanks

Yes .of course . Thanks

**Comment by BlackEagle1983** [comment] 2022-07-26 08:50
[test.zip](https://github.com/UPBGE/upbge/files/9188186/test.zip)
This is the test file . The Issue is in Logic Brick Node View Section .

**Comment by IzaZed** [comment] 2022-07-26 09:08
This is an issue with the bricky nodes addon, not upbge itself (I think)
I will check it out later this week

**Comment by youle31** [comment] 2022-07-26 09:54
I can't reproduce the crash in last master. Imo it could be a blender bug which has been fixed like: beb746135dbe0c5ca21c2334e7dc475f201ad71e or similar

**Comment by IzaZed** [comment] 2022-07-29 19:11
It does seem to be a blender bug as it's working in UPBGE 0.31 and the bricky node addon was last updated before that version was released

**Comment by youle31** [comment] 2022-07-30 03:21
I'll investigate on this later (at autumn maybe). I managed to reproduce it on my other PC.

(It is either a Blender bug, either maybe a bug related to bpy.ops.logic undo changes done few monthes ago)

**Comment by youle31** [comment] 2022-09-27 09:53
Hi, I did a build with a potential fix here: https://ufile.io/i8efpi3z for windows 64.

Could you test and see if bricky nodes is still crashing or if there are other anomalies? Thank you

**Closed** 2022-09-27 19:30 UTC
Labels: 0.3+
