### ISSUE TITLE
upbge 0.2.5 crash when I bevel the face twice

### ISSUE THREAD

**Issue by Debug-Enger171** [UPBGE/upbge#1467] opened 2021-05-03 17:43 UTC
* Sorry my english, i'm brazilian and i'm using the translator

for example, if I apply a bevel to the entire cube and then try to apply another bevel to any face or edge or vertex the upbge simply closes, if I apply it in edit mode only on a corner to make the cube a ramp and try to apply a bevel again on the sloping face of the ramp the upbge simply closes, it does not happen in the upbge 0.2.4, I have already updated drivers, formatted the computer and nothing resolves, running the console the upbge returns an error:
Error: Unrecognized Exception
Address: 0x00007FFB8E7B3FB8
Module: C: \ Windows \ System32 \ KERNELBASE.dll

* novamente perdoe o inglês, eu realmente preciso da sua ajuda

**Comment by AC-Panda** [comment] 2021-06-14 01:48
# Bug Reported in 2019
https://forums.chaosgroup.com/forum/v-ray-for-blender-forums/v-ray-for-blender-bugs/1031848-blender-with-v-ray-additions-crashes#post1031896

# Solution
https://forums.chaosgroup.com/forum/v-ray-for-blender-forums/v-ray-for-blender-bugs/1031848-blender-with-v-ray-additions-crashes?p=1032329#post1032329

**Comment by youle31** [comment] 2021-09-05 05:12
I can't reproduce anymore this bug in last 0.2.5 on my last windows OS. I also guess it comes from windows OS environment and not from Blender, then I close this issue.

**Closed by youle31** 2021-09-05 05:12 UTC
Labels: 0.2.5

**Comment by Debug-Enger171** [comment] 2021-09-10 02:49
Other people have also reported the problem, it's not something about the UPBGE or blender version, it seems to have to do with .net framework and Microsoft Visual C++. I solved it for myself by installing .net framework and all compatible versions of Visual C++, for that I used vcredist (https://github.com/abbodi1406/vcredist/releases). Thanks for all the support.
