### ISSUE TITLE
Issue with "for key, input in sensor.inputs"

### ISSUE THREAD

**Issue by RedstarBelg** [UPBGE/upbge#1162] opened 2020-03-31 11:33 UTC
Hello,

I found something wrong with this code: "for key, input in sensor.inputs". Python return this: "TypeError: 'int' object is not iterable".

But this code is written like that in the wiki. The old "for key, input in sensor.events" work perfectly but i have this warning message:

"Warning: my_script(line_code), method sensor.events is deprecated, please use sensor.inputs instead."

Is there a bug or human mistake ?

**Comment by RomStef** [comment] 2020-03-31 13:15
i'm trying to reproduce the error

import bge
own = bge.logic.getCurrentController().owner
for key, input in own.sensors["Keyboard"].events :
    print(key,input)

![image](https://user-images.githubusercontent.com/20901566/78030070-d45b5a00-7361-11ea-9768-7c268a619478.png)

no error return with my code.

**Comment by RedstarBelg** [comment] 2020-03-31 13:23
Hello RomStef,

In the wiki of upBGE the new method is **`for key, input in sensor.inputs`**
In the wiki of BGE 2.79 **`for key, input in sensor.events`**

It the new method who wrong.

**Comment by RomStef** [comment] 2020-03-31 16:58
if you use bge.logic.keyboard.inputs[bge.events.SOMEKEY] or sensor.inputs[bge.events.SOMEKEY] you can test directly the properties : Active , Inactive , Activated and Released.

http://shuvit.org/python_api/bge.types.SCA_InputEvent.html#SCA_InputEvent

i suggest you to print the class method and properties to screen and dig into the problems you want to solve.
 
my method to detect the keypress is for example :

if bge.logic.keyboard.inputs[bge.events.WKEY].active : 
-> move forward

**Comment by RedstarBelg** [comment] 2020-03-31 17:19
`for key, input in sensor.events` works. So why who is the charge of the improvement about the python part of the upBGE change the method for the new version if this method doesn't work ?

Between, somebody can tell me what the status of the improvement of the upBGE ? The last information i have is the team in charge is broken, it's correct ?

I can't solve the problem myself, i don't have enough knowledge to play with source code. I don't know how to compile or decompile it anyway.

I just want to report the problem. Stay in version 2.79 from the BlendFoundation is the same for me, you know.

**Comment by RomStef** [comment] 2020-03-31 17:34
@youle31   and @lordloki still works on upBGE and ported it in blender 2.8 as upBGE 0.3.0 Alpha. I don't know why the keybord sensor method changed but it works for me without errors. maybe if you can post an example file i can try to help you

**Comment by RedstarBelg** [comment] 2020-03-31 19:42
from bge import logic as gl
from bge import events as ev

scene = gl.getCurrentScene()
obj = gl.getCurrentController().owner

for key, statut in obj.sensors['chx_key'].events: # here, i should replace with input but the error is here for python
           if statut == gl.KX_INPUT_JUST_ACTIVATED:
                   if key== ev.ENTERKEY:
                        obj['assign'] =
                        var_player['name'] = obj['give_name']
                        obj['give_name'] =
                    
                 elif key == ev.BACKSPACEKEY:
                        obj['give_name'] = obj['give_name'][:obj['limit_char_nam'] - 1]
                        obj['limit_char_nam'] -= 1
                        gl.text_main[0].text = obj['give_name']
                    
                 elif key == ev.RIGHTSHIFTKEY or key == ev.LEFTSHIFTKEY:
                        obj['shift'] = True

**Comment by RomStef** [comment] 2020-04-01 19:24
i have found some issue but this code should work

![image](https://user-images.githubusercontent.com/20901566/78177880-1c13db80-745f-11ea-8f38-4360846f2120.png)

![image](https://user-images.githubusercontent.com/20901566/78177900-21712600-745f-11ea-908e-0826a5a3da67.png)

**Comment by RomStef** [comment] 2020-04-01 19:31
@ youle31 @lordloki I have encountered some problems with the SCA_InputEvent class.

inactive, active, activated and released properties no longer exist.
bge.events.ENTERKEY no longer exists.

maybe the code is misaligned compared to version 2.4b

**Comment by youle31** [comment] 2020-04-01 23:44
upbge 0.3 is based on an "old" version of upbge (this is based on a version between 0.1.7 and 0.1.8 iirc). The code has changed slightly concerning events after 0.1.8, then what you can look in the 0.2.4 API is not necessarly in upbge 0.3 which had a slightly different system.
I'll add a mention on the "development ideas" thread to see if we can recover commits related to events after 0.1.8

**Comment by youle31** [comment] 2020-04-02 00:33
I upload a tesfile i just did to see how are working events (because even if there's a warning message, I often use the old system):

https://pasteall.org/blend/fc9e4cbe5faa4dbab149724e3d08364d

**Comment by RedstarBelg** [comment] 2020-04-02 07:31
I'd like to precise the error i see it was on the 0.2.3 version upBGE. The code RomStef has written should be logic about the "int" input profile.

Nobody has try to make a game or a "special" blend with the new upBGE items to verify them ?

**Comment by lordloki** [comment] 2020-04-03 06:07
inactive, active, activated and released properties were just recovered in last build.

**Comment by RedstarBelg** [comment] 2020-04-03 07:30
The 0.2.4b ? It is more stable and reliable now ?

**Comment by lordloki** [comment] 2020-04-03 07:32
No, i was referring to last upbge 0.3 alpha build

**Comment by RedstarBelg** [comment] 2020-04-03 07:44
Oh, i understand. This is for EEVEE engine, right ?

I need actually something reliable for building my game and i'm not yet ready to use the node system with EEVEE, i have so much to learn from the BGE itself, even if i have a modest global level now about it.

**Comment by youle31** [comment] 2020-04-16 02:54
Indeed the API for sensor.inputs seem false and sensors.inputs only return an integer (idk for keyboard.inputs). But the API is hosted by shuvit and I don't know if we'll recompile it.
As it's a minor issue, I close this task.

**Closed by youle31** 2020-04-16 02:54 UTC

**Comment by BluePrintRandom** [comment] 2020-04-16 03:17
yeah I used this today

swapped from event[0] to event
