### ISSUE TITLE
Segmentation fault accessing worldPosition

### ISSUE THREAD

**Issue by vlad0337187** [UPBGE/upbge#950] opened 2018-11-25 00:21 UTC
Steps to reproduce:
- get some object
- change object's local position
- after try to access (copy) it's world position - Segmentation Fault

OS: LInux Mint 19 Cinnamon
Kernel: 4.15.0-39-generic
UPBGE: 0.2.4

**Comment by panzergame** [comment] 2018-11-25 10:03
Can you provide and example file ?

**Comment by vlad1777d** [comment] 2018-11-29 15:16
Still can't reproduce it.
I accidentally changed code and don't remember which combination made 100% crash.
I even think, maybe https://github.com/UPBGE/blender/issues/952 caused that crash, which I noticed as 100%.
But I remember it was bound with worldPosition, because I commented that line and all worked.

I'll try to find such combination.

**Comment by lordloki** [comment] 2020-04-25 08:09
I can't reproduce it in 0.2.5.
Closing the issue. Thanks for reporting

**Closed by lordloki** 2020-04-25 08:09 UTC
