### ISSUE TITLE
 Fps drop in upbge 0.3

### ISSUE THREAD

**Issue by HolandonHdunto** [UPBGE/upbge#1670] opened 2022-02-25 01:12 UTC
In upbge 0.3 on certain computers mainly weaker computers with video card, notebooks or computers without video card, there is colossal fps drop when adding new objects to the scene, the problem remains even if the added object is only composed by one vertex, without any kind of material or modifier.

Here is a sample of the problem:
https://m.youtube.com/watch?v=_tPeXkjodDU&t=141s

**Comment by rpaladin** [comment] 2022-02-25 01:19
For UPBGE 0.3+, same as latest UPBGE releases, it is strongly recommended to use [recommended](https://www.blender.org/download/requirements/) computer specs for optimal performance.

![image](https://user-images.githubusercontent.com/69180012/155635214-d10f35d5-da36-4219-9de0-c31d156faf98.png)

**Comment by lordloki** [comment] 2022-02-25 09:53
This is not a bug. This is a known design weak that we are trying to solve/mitigate/improve.

More in deep, this fps drop, when an object is added, is due to a depsgraph relations recalculation and it is, more or less, independant of the Object's triangles.

I close the issue as it is not a bug per se although we are working on it. Thanks for reporting.

**Closed by lordloki** 2022-02-25 09:53 UTC
Labels: performances
