### ISSUE TITLE
C++ extensions

### ISSUE THREAD

**Issue by Liebranca** [UPBGE/upbge#1088] opened 2019-12-11 11:32 UTC
Hey gang,

Went back to writting mostly cpp recently. It's easy enough to extend python through dll/so/pyd, so I thought great, I'll just use something like boost to handle game types and rewrite my libraries -- but then I ran some tests, and the performance one gets when passing around python objects isn't all that great.

Thus I began wondering, there might be a way to reference the "real" object underneath the python exposure. My gut tells me this shouldn't be too hard, but I'm obviously missing something here or else I'd figured it out already. Is this in the realm of possibility or am I just wasting time?

**Comment by marechal-p** [comment] 2019-12-11 15:26
I don't think Blender natively handles loading "pluggable shared libraries", and if not you could setup a small support for it maybe, not that hard.

- dlopen on Unix like (Linux + Mac): https://linux.die.net/man/3/dlopen
- LoadLibrary on Windows: https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya

So you'd need to write a small abstraction to, well, abstract away platform specifics. Then you'll need to manage to get header files that you can distribute to people for making plugins. These header files will define the ABI for the plugins. Then somehow hook that up to Blender/BGE.

I jumped quite a few steps, but this is what I would expect you'd have to do, roughly.

**Comment by marechal-p** [comment] 2019-12-11 15:28
Right now Blender doesn't load shared libraries (containing native code that could interact with the process memory directly), but since it runs a Python virtual machine it can dynamically load scripts. I am just not sure that you can make Python native extensions that would be able to breach out of the Python VM's context and access the wrapped Blender native objects. But please someone prove me wrong.

**Comment by Liebranca** [comment] 2019-12-16 02:48
Dug around a little bit and it seems I can't get what I want without forking. Bummer.
So, plan B: I'll have to waltz around with ctypes.

**Comment by marechal-p** [comment] 2019-12-16 19:58
> I can't get what I want without forking.

Can you expand?

**Comment by Liebranca** [comment] 2019-12-16 21:44
There is no method (that I've been able to find) to return the real address of an object, only that of it's python representation through `id()` -- and we can only cast that into a pointer to a PyObject, so it's back to square one. Moreover, the number of source files that need to be included is off the charts.

The less frustrating solution for now is to extract the data I need and cache it when necessary.

**Comment by marechal-p** [comment] 2019-12-16 22:09
Could be that you just need to add a new property to these PyObjects, such as the pointers to the wrapped internal objects. Then maybe you can cast these to pointers to Blender's native structs? You'd need to "fork" and eventually submit a Pull Request to see it merged here, if people are interested :)

**Comment by Liebranca** [comment] 2019-12-16 22:51
Yes, that's about right; not impossible but most definitively a chore to go through.
I'll give it a try but totally not right now, I have some other headaches to deal with.
Also thank you c:

**Comment by youle31** [comment] 2020-06-30 05:04
I'm not sure i understand (I'm almost sure i didn't understand...), but you can get an ID (the struct used for almost all Object types internally by blender) from a PyObject with this API: bool pyrna_id_FromPyObject(PyObject *obj, ID **id) and there is the API to create an ID from a PyObject: pyrna_id_CreatePyObject(ID *id)... Sorry if it doesn't help.

As the issue is old, and that I try to do a bit of cleanup, I close it for now.

**Closed by youle31** 2020-06-30 05:04 UTC
