### ISSUE TITLE
Running the game engine from headless mode crashes blender

### ISSUE THREAD

**Issue by Mattline1** [UPBGE/upbge#1635] opened 2022-01-15 22:37 UTC
# Issue:
Attempting to run the game engine in headless mode by calling bpy.ops.view3d.game_start() will cause blender to crash.

The following code triggers the crash.
```
import subprocess

# the path to UPBGE blender.exe install location
blender_executable = "PATH TO UPBGE EXECUTABLE GOES HERE"

# the expression to be run in blender once loaded
# simply import bpy then run the engine
expr = """
import bpy
bpy.ops.view3d.game_start()
print("!!!Comment out the above line and this should appear in the console !!!")
"""

# run the executable in headless mode "-b"
# pass the expression to run in blender "--python-expr"
args = [blender_executable, "-b", "--python-expr", expr]

# run the subprocess
process = subprocess.run(args)

# Crash! 
# Error   : EXCEPTION_ACCESS_VIOLATION

# if it doesn't crash, print it's output
print(process.stdout)
```

# Expected behaviour:
It shouldn't crash on starting the game engine.

Preferably, the script sent to blender should halt until the game engine has exited, i.e. bpy.ops.view3d.game_start() should behave like a blocking function. Or the automatic closure of blender that occurs once a headless script has completed should be deferred until the game engine has closed.

**Comment by lordloki** [comment] 2022-01-15 22:47
Headless mode is a mode for rendering only and it is not prepared for game engine use. 
The issue is that the game engine expects that graphics part is ready when it tries to raise itself. Due to this, it crashes.

Headless mode for game engine is a known feature request and it is in our TODO but it is not a priority feature.
I close this issue. Thanks for the feedback.

**Closed by lordloki** 2022-01-15 22:47 UTC
