### ISSUE TITLE
Scene Restart actuator not working in UPBGE eevee 0.3 Alpha (2020-04) 

### ISSUE THREAD

**Issue by chicortiz** [UPBGE/upbge#1183] opened 2020-04-16 21:31 UTC
Hello Dear UPBGE folks!

Looks like that the Scene Restart actuator is not working in UPBGE Eeevee. I tested the file bellow in:

UPBGE-EEVEE-Linux64-2020-04-06
And
UPBGE-EEVEE-Linux64-2020-04-14

And it's not restarting the scene.

Download .blend file for test here: 
https://drive.google.com/file/d/12x5hNWBPcjmE2d-g2R-pzfpuvdxVIv0s/view?usp=sharing

I wish you all the best, 

Greetings,

Ortiz

**Comment by youle31** [comment] 2020-04-16 23:30
hi, yes, restart actuator has issues, it has been reported here: https://github.com/UPBGE/upbge/issues/1154
I'll copy your report into the first bug report and close this one.

**Comment by chicortiz** [comment] 2020-04-17 15:19
Thank you for your attention Youle! :)

**Comment by youle31** [comment] 2020-04-24 07:50
I reopen this as I mixed restart scene actuator and restart game actuator

**Comment by youle31** [comment] 2020-04-24 08:37
Note for myself:
We need to undo/redo each time we start/exit KX_Scene...

**Comment by chicortiz** [comment] 2020-04-24 15:34
Hello Youle! Hello folks!

Other information that maybe is useful: The scene restart actuator was functioning in build (2020-01-29) / Blender 2.8 eevee.

Greetings,

Ortiz

**Comment by RomStef** [comment] 2020-04-25 17:18
not only "restart" doesn't work in scene actuator , "set camera" also

**Comment by youle31** [comment] 2020-04-25 17:29
SetCamera should work if you are in camera view when you launch game engine.
Else, blender code doesn't set the view matrix if you are not in camera view then it is not a bug but a limitation compared to 2.7 bge

**Comment by youle31** [comment] 2020-04-28 04:15
I spent some time to try to have undo working when we Set/Replace scene, but I don't manage to have it working.

We can just backup gameobjects worldtransform at scene start and restore it at scene exit, but the other changes that we could do on meshes, light data, materials... won't be "un-done" until game exit.

I propose to do that for now and we can maybe see later if we understand better how undo works.

I'll do a commit to backup/restore obmat when i'll be motivated a bit later.

**Comment by youle31** [comment] 2020-04-28 12:01
Temporarly fixed here even if this is not an ideal solution: https://github.com/UPBGE/upbge/commit/f04a53e54a92cdd6ce8f90296a197909443f9c6e

**Closed by youle31** 2020-04-28 12:01 UTC
Labels: 0.3, bug
