### ISSUE TITLE
Versioning chaos and request for UPBGE build that supports blender 2.92

### ISSUE THREAD

**Issue by Illasera** [UPBGE/upbge#1653] opened 2022-02-09 15:22 UTC
A.)I have no idea what's going on with the versions.

I tried to download UPBGE 0.25, as soon as i unzip it , i see there is dependency on blender version 2.79
While some files were actually updated up to 2021, So which one is it?

I understand its a fork but its very hard determine on which version the fork is currently based on.
Even in the release notes, i can make heads or tail out of it.

B.)I am looking for a version that works with blender 2.92 or 2.91.

(For those of you who don't know, Windows 7 support was dropped at blender 2.93+)
10% of the market still uses windows 7.

Now, i know that there was a 3.0 alpha version that used blender 2.91 or 2.92, Where can i find a mirror of it to download?

(Yes, the right place for such info is under github issues since i can't find better way to communicate with the team behind this project).

**Comment by lordloki** [comment] 2022-02-09 16:34
Hi,
In this link you have the last official releases: https://github.com/UPBGE/upbge/releases
And specifically, in this link you have the UPBGE 0.3 build, based in blender 3.0, and additionally it works for windows 7: https://github.com/UPBGE/upbge/releases/download/v0.30/UPBGE-0.30-windows7-x86_64.7z

**Comment by Illasera** [comment] 2022-02-10 16:27
How come your fork is working on windows 7, did you guys not update the 3rd party libraries that blender uses?

Or maybe the blender team switched to a newer compiler, I have no idea what caused the compatibility change,

The question is, how come your version works on windows 7?

**Comment by lordloki** [comment] 2022-02-10 16:48
We adapted this solution from @nalexandru https://github.com/nalexandru/BlenderCompat

In that link you can find no officials Blender 3.0 builds that works in Windows 7 too.

I close this report now. Thanks for reporting.

**Closed by lordloki** 2022-02-10 16:48 UTC

**Comment by Illasera** [comment] 2022-02-10 16:49
Before you do, Mind that the current version is giving some false positives when scanning blender binaries , While it is false positives by 1 AV , it is discouraging and should be looked into the cause of it.

**Comment by lordloki** [comment] 2022-02-10 17:18
The cause is that the heuristic analysis of the antivirus is very poor. Anyway, checking it, in around 93 antivirus, it doesn't report positive in anyone:
https://www.virustotal.com/gui/url/95b0330216883bdca39be5cd9d00b9d48f1bc996a6af9bee8a180169a8bde670?nocache=1
![image](https://user-images.githubusercontent.com/1015605/153461004-62eecb77-2bbb-499a-8b77-c91b9e41465a.png)

**Comment by Illasera** [comment] 2022-02-10 19:41
I assume virustotal doesn't know what to do with archives, there are no "Details" on such scan,

Further evidence is found here at scanning blender UPBGE binary file (Current version on release in link above)

https://www.virustotal.com/gui/file/a25f29d60c1a6b3b4ead3f3932539efa1e848099ad2d954bc13a083e0a67fe02
https://www.virustotal.com/gui/file/505abd79cfbeac118ff24652f9f29fce2440e399e8b40acbf85d6849373fd237
https://www.virustotal.com/gui/file/fa78a126a72f1f57221008ac15fb14931c09be65e65553083a37a0bd17e8ac2f

links above for blender upbge (Current version)
Blender launcher (Current version)
Blender player (Current version)

A.)If there is content inside the archive that is detected as malicious , that means that the archive scan on virustotal is moot (How can the archive is clean but the content in it , isn't? simple, virustotal doesn't detect archives)

B.)Please attempt to find what causes such false positives and fix them in future releases as well as current release to ease up our minds, Thanks in advance.

**Comment by lordloki** [comment] 2022-02-10 20:30
The same occurs if i upload the blender.exe (3.2 alpha) from daily builds, as you can see in the link:

https://www.virustotal.com/gui/file/978cb3a2c45c268e88ce147ec6c50419ff96fa0bf1dabb4bbc493bc5c7f3ff60/details

As I said before the cause is that the antivirus heuristic is a shit. We are not going to spend any time to avoid the antivirus wrong behaviour.

**Comment by Illasera** [comment] 2022-02-10 21:18
Yes sir, i can understand that.
