### ISSUE TITLE
Second Python Module Controller does not work. 

### ISSUE THREAD

**Issue by Shohrukh1999** [UPBGE/upbge#1194] opened 2020-04-26 08:54 UTC
Hi, **UPBGE developers!**
I created two planes, one of which ***should turn on/off*** the *FullScreen,* and the second ***should turn on/off*** the *FrameRate,* when you click *LMB* on them.
For them, I created a ***simple script*** with two modules (functions?).
When I start, only *FullScreen Toggle works,* and *FrameRate Toggle does not work.*
After starting, ***look at the console***. It says that allegedly the *FrameRate Property do not exist.*
But, when I **delete the plane responsible for switching the FullScreen,** the plane responsible for switching the *FrameRate will suddenly work.*
P.S. I am a ***beginner coder,*** I don’t know much, and I need to learn a lot. **Perhaps I made a mistake somewhere.**
[BUG.zip](https://github.com/UPBGE/upbge/files/4534934/BUG.zip)

**Comment by lordloki** [comment] 2020-04-26 11:53
The issue is that the first can read the whole script but the second call only the function.

If you set-up the script this way:
```
import bge

def FullScreen():
    cont = bge.logic.getCurrentController()
    own = cont.owner

    if own['FullScreen'] == True:
        bge.render.setFullScreen (True)
    else:
        bge.render.setFullScreen (False)
        
def FrameRate():
    
    cont = bge.logic.getCurrentController()
    own = cont.owner
    if own['FrameRate'] == True:
        bge.render.showFramerate (True)
    else:
        bge.render.showFramerate (False)
```
The functions will work for both planes

**Comment by lordloki** [comment] 2020-04-26 11:54
Closing now. Thanks for reporting.

**Closed by lordloki** 2020-04-26 11:54 UTC

**Comment by Shohrukh1999** [comment] 2020-04-26 12:19
Thank you so much, @lordloki!
