### ISSUE TITLE
Compositing Error

### ISSUE THREAD

**Issue by FayerOutlook** [UPBGE/upbge#1905] opened 2024-07-22 17:33 UTC
An error occurs in the Compositing overlay. The overlay depends on the 3D Viewport window

File for UPBGE version **0.43 alpha** (The error is also present on earlier versions):
[Incorrect-Compositing-scale.zip](https://github.com/user-attachments/files/16337757/Incorrect-Compositing-scale.zip)

![image](https://github.com/user-attachments/assets/b8630d8f-518f-4ab1-bfb8-5866b34b586f)
![image1](https://github.com/user-attachments/assets/50286094-bcd6-4a61-b57f-8872b4fba8bd)

**Comment by BluePrintRandom** [comment] 2024-07-22 21:51
closed as duplicate of https://github.com/UPBGE/upbge/issues/1904

**Closed by BluePrintRandom** 2024-07-22 21:51 UTC
