### ISSUE TITLE
UPBGE 0.2.5 on MAC keep freezing with operation linked to textures

### ISSUE THREAD

**Issue by Trample-ingame** [UPBGE/upbge#1215] opened 2020-05-31 09:25 UTC
upbge freezes when: 
- undo after packing an image
- selecting an image from the computer by the texture panel
- after added parallax to a texture if i undo or assign a lamp to more than two layers it freezes again
- i tried with this version my game that i'm building with 0.2.4 but i had crazy logic bricks ignoring some properties. so i keep with 0.2.4

**Comment by lordloki** [comment] 2020-05-31 10:58
I will test in the macosx test server. Maybe i have to build from there

**Comment by Trample-ingame** [comment] 2020-05-31 12:01
ah i forgotten to say that it crashes even when closing it

**Comment by lordloki** [comment] 2020-05-31 12:28
Could you test with this build?
https://mega.nz/file/gkshxbqa#P_8qjZGfOnhInjB4q6X8d_4DNG09nXMRheDvBbTqQ-I
Thanks

**Comment by Trample-ingame** [comment] 2020-05-31 15:05
still freeze in same situations

Il giorno dom 31 mag 2020 alle ore 14:28 lordloki <notifications@github.com>
ha scritto:

**Comment by lordloki** [comment] 2020-07-05 01:26
Only for info. 
The issue is in this commit 0276e0e7de4a where all the macos libraries were updated (python 3.6 to 3.7, etc). I'm trying to do a mix with old libraries and new libraries to get a good build (at this moment i can't build at all).

**Comment by Trample-ingame** [comment] 2020-07-05 08:29
ok thanks
shouldn't i touch nothing of script right?

Il giorno dom 5 lug 2020 alle ore 03:26 lordloki <notifications@github.com>
ha scritto:

**Comment by lordloki** [comment] 2020-07-07 11:19
Here you have a new build. It seems fixed (although I only tested loading of images and undo after packing).
If everything is ok for you I will use this way to next UPBGE 0.2.5b release

**Comment by Trample-ingame** [comment] 2020-07-07 14:31
I tested all i done with the alpha and now it doesn't freeze anymore for these points

**Comment by lordloki** [comment] 2020-07-07 15:12
Ok, then I close this issue. If you find another freeze related to this, please reopen the issue.

Thanks for reporting.

**Closed by lordloki** 2020-07-07 15:12 UTC
Labels: 0.2.5, bug
