### ISSUE TITLE
Upbge 0.3 standalone/export crash

### ISSUE THREAD

**Issue by corryVanr** [UPBGE/upbge#1176] opened 2020-04-12 20:06 UTC
Hi guys 
Having a issue with upbge 0.3 build 2020-04-10 23:30

When i press "P" the game runs fine and i can save and load to globalDict
But if i use the built in stand alone player or if i export to a game file it'll crash as soon as i press either to save or to load my progress 
At first i thought it was deu to poor game optimisation so i made a straightforward cube and platform setup with the same issue 
The same happens in any of the builds before aswel
There is also a Totblock error : 119

Any help would be greatly appreciated I've been struggling for two days now i don't know what can cause this issue

**Comment by youle31** [comment] 2020-04-13 06:43
Could you provide a simple test file and describe exactly the steps to reproduce the bug? Thanks

https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide

**Comment by corryVanr** [comment] 2020-04-13 10:05
https://drive.google.com/drive/folders/1nU2aHZO5uBDGoeFx9DyzmMa_BWDWjd2O?usp=sharing

here is the link to the mock up blend file 

i'm using UPBGE-EEVEE-Win64-2020-04-11 atm and the file was made on UPBGE-EEVEE-Win64-2020-02-21

i'm using windows 10 Home
CPU : i7-6700HQ @ 2.60GHZ
GPU : Gtx970M 3Gb
RAM : 16Gb DDR4

when you start up blender open the file and press P all works 100% the keys ('m' to start game,at startup menu) ('G' to save in game) ('L' to load on start up menu) 

but when using the Standalone player at times it'll just open and close and if it dose open it'll crash if i try to load or if i try to save in game ,,,if i disable the globalDict's scripts by the logic editor both the load and save then the game will start up and can play but then obviously i can't save  
it also kills the console so i can't see the error's

**Comment by corryVanr** [comment] 2020-04-13 10:06
also both the UPBGE's i got from the site upbge.org from the mega drive

**Comment by corryVanr** [comment] 2020-04-13 10:19
press on startup 'L' to load then 'M' to start the game 'L' doesn't automatically start the game

thank you very much

**Comment by youle31** [comment] 2020-04-14 14:44
The filename for this file seems corrupted, i have no idea why. The debugger says the filename ends with a "~" and it seems to cause path issues. Could you try to append your scenes in a new .blend and see if it works?

**Comment by corryVanr** [comment] 2020-04-14 14:49
do you know what can cause such corruption  
ok i'll quickly try that and see what happens

**Comment by corryVanr** [comment] 2020-04-14 15:01
ok i just done as you asked and it still crashes the game even in the embedded play

**Comment by corryVanr** [comment] 2020-04-14 15:05
https://drive.google.com/drive/folders/1YC4Q__aeZkgNTYPF-xh1lM7j8yAA32nb?usp=sharing

here is the link for the backup version of the blend file ,but its just the blend file

**Comment by youle31** [comment] 2020-04-14 15:41
Note for myself or lordloki: What I saw in the debugger is that in write.py, when you comment LoadGlobalDict, it doesn't crash.
In Internal code, when you comment KX_PythonInit::  ... std::string marshal_path = pathGamePythonConfig(); , it doesn't crash. Idk if this can be related to BLI_path cleanup done by campbell barton or a merge mistake I did or something else.

@corryVanr : Do you have this crash since a long time or?

**Comment by corryVanr** [comment] 2020-04-14 15:48
i see,that's strange
no this crash recently started happening about 4 days ago
i thought that it might have been the upbge build that's why i re downloaded the latest one at the time 

do you have any suggestions to what i can do or where to go from here?

**Comment by youle31** [comment] 2020-04-14 15:56
No, Blender coders did modifications in the code recently related to path (BLI_path). We need to check in the log what they did to fix the bug. Knowing that you have this crash only since 4 days will help us to debug. We have to check KX_SetOrigPath and in GPG_Ghost there were some things changed too.

This could be related to some merges I did recently (We'd need to check the occurrences of BLI_path_normalize in bge code and BLI_path_abs_from_cwd and see what can be wrong in the merges i did.

**Comment by corryVanr** [comment] 2020-04-14 16:03
Ok i see
i want to thank you allot for the support and quick responses i really appreciate it and the work you guys are doing on the engine is brilliant to say the least 

i'm just going to carry on as usual as it seems to be stable enough when i use the embedded player 
so ill refrain from exporting the files and keep my saves to a minimum
i was thinking of running upbge in a sandbox ,or would that be deemed unnecessary?

if it is any help the totblock errors i got was '119' , '115' that i can recall

**Comment by youle31** [comment] 2020-04-17 02:25
I pushed a "fix" in master, I tested with this simple file: https://pasteall.org/blend/b49284f2052e4ad39218f0c5f72d4d52

It is working for me now. When lordloki will do a new build in the next days, you can try again with your file if the crash is solved and close this report.

**Comment by lordloki** [comment] 2020-04-17 05:24
builds ready

**Comment by corryVanr** [comment] 2020-04-17 09:23
Hi Guys thank you for the tremendous effort you guys are awesome
 i'm downloading the new build at the moment 
will post as soon as its done

**Comment by corryVanr** [comment] 2020-04-17 09:50
Hi Guys thank you for the tremendous effort you guys are awesome
 i'm downloading the new build at the moment 
will post as soon as its done

**Comment by corryVanr** [comment] 2020-04-17 10:06
forgot the hit 'Comment' for the previous msg

all is working 100% in the stand alone player and the exported game version i cant begin to express my gratitude, you guys are insanely good at what you do, thanks a million again 
how and where can contribute to you guy's work in terms of a monthly contribution
as, as soon as the lock-down is lifted here by me id like to contribute in any i way can

**Comment by youle31** [comment] 2020-04-17 10:43
Great! If all is working i'll close this task.
Thanks very much @lordloki  for the build.
About financial contributions, I don't accept it personally, neither lordloki.

**Closed by youle31** 2020-04-17 10:43 UTC
Labels: bug
