### ISSUE TITLE
Weird collision (Dynamic vs Static)

### ISSUE THREAD

**Issue by RockyMadio** [UPBGE/upbge#884] opened 2018-10-10 17:39 UTC
http://pasteall.org/blend/index.php?id=50486

You move the cube with D to the right, against the wall

in 0.2.3, things work flawlessly
in 0.2.4, the wall keeps on pushing the cube back

**Comment by panzergame** [comment] 2018-10-14 09:12
The user must never use teleportation for moving objects without "preventing" bullet. For such movement he must use the object velocity.

And the position will be changed by : velocity * dt
Where dt is the delta frame time.

Teleporting object could cause them to be inside others, old bullet is kind of managing the issue but the recent bullet version don't. And I don't think we can expect more from physics engine as this case isn't supposed to happen if the physics has full control of the object position.

@lordloki, @youle31, @marechal-p : Do we have to make a note on documentation ?

**Comment by lordloki** [comment] 2018-10-14 09:42
Yes, i think a note would be necessary.

**Comment by BluePrintRandom** [comment] 2018-10-14 09:49
what about the default behavior to be to raycast from start of move to end
of move and place object based on ray hit?

we could use batched raycast api and solve all DLOC motion in 1 shot.

**Comment by marechal-p** [comment] 2018-10-14 13:51
@BluePrintRandom Bullet does clever checks when using velocity in order to not fuze the geometries (based on the bounding boxes).

Doing a simple raycast when actually teleporting yourself using `applyMovement` is counter-productive, because if you only fire one, how do you ensure that the shape truly never merge with an obstacle. DO you raycast from each vertex? No: you use velocities and let Bullet do the job.

@panzergame @lordloki +1 for documentation. People should understand that teleporting objects by changing the position directly will lead them with things stuck in walls.

Is the problem still there when setting the velocity? If not then documentation alone is good.

**Comment by Cotaks** [comment] 2018-10-14 16:15
> Is the problem still there when setting the velocity? If not then documentation alone is good

I can confirm that the issue is NOT present when using velocity, but this was always an issue even in BGE itself, that's why i always use velocity to move my objects. velocity and applyForce does not teleport the object, all other methods do. (not tested force in this case, but that's what i know)

**Comment by BluePrintRandom** [comment] 2018-10-14 17:16
yeah @Paul - I was thinking we could raycast for each corner of a box, and
about 2x more points for a sphere,
and all veretx for a triangle mesh / concave

using batched raycast we can do all the raycasts in almost the same time as
1 traditional raycast.

**Comment by ethicalfive** [comment] 2018-10-16 16:12
wasn't the version of bullet rolled back in the latest source? This behavior still exists?

**Comment by panzergame** [comment] 2018-10-16 17:46
Yes, it still exists.

**Comment by youle31** [comment] 2020-07-04 13:06
As we choosed to base 0.2.5 on old bullet, I close this issue

**Closed by youle31** 2020-07-04 13:06 UTC
Labels: bug
