### ISSUE TITLE
UPBGE 3.0 crashes when I try to use Levels of Detail

### ISSUE THREAD

**Issue by cholm1891** [UPBGE/upbge#1512] opened 2021-07-03 19:46 UTC
Hello,
I am having trouble with levels of detail. I can set them up for an object, but as soon as I zoom out far enough for the mesh to change, the program crashes. Here is the debug log. 
[steve.crash.txt](https://github.com/UPBGE/upbge/files/6758965/steve.crash.txt)

**Comment by youle31** [comment] 2021-07-05 13:02
Hi, could you provide a .blend to reproduce the issue? Thanks!

**Comment by cholm1891** [comment] 2021-07-05 14:04
Actually, studying it further, I found out that it only happens with a few specific files so it's most likely a problem on my end. Here are the files if you want to take a look.
https://drive.google.com/file/d/13EQ0-8V3D28Ooenqs74zMLHaUyMmOQVg/view?usp=sharing
https://drive.google.com/file/d/1j0_tyzDGXJR2wggB1DF3WTd9xDYTm61_/view?usp=sharing
https://drive.google.com/file/d/1yYVAYkZokxDkXgAPtgYWBwOXRDQJBRHo/view?usp=sharing

**Comment by youle31** [comment] 2021-07-07 22:46
I confirm the bug in the third .blend due to weak implementation of LOD

**Comment by youle31** [comment] 2021-07-13 04:44
Normally fixed in mentionned commit, thanks for report

**Closed by youle31** 2021-07-13 04:44 UTC
Labels: 0.3, bug
