### ISSUE TITLE
GPU to Services!?

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/upbge#1014] opened 2019-02-12 13:12 UTC
![serv_gpu](https://user-images.githubusercontent.com/35436445/52637593-d260de00-2eb6-11e9-80c7-8586734c3644.gif)
could anyone explain this imbalance between: GPU and Services?

**Comment by UglinessInTheUI** [comment] 2019-02-17 00:42
There is something wrong in your blend file. Can you upload it so i can test it on my system ?

**Comment by EndSSgamesStudio** [comment] 2019-02-17 02:47
@UglinessInTheUI  http://pasteall.org/blend/index.php?id=51228

**Comment by UglinessInTheUI** [comment] 2019-02-17 04:31
It's not working properly on my computer either. I will have to try a few extra things like remove all the logic controllers and rebuild the scene from scratch. Mouse Look actuator is creating a lot of stuttering. It's not very smooth at all. I will have to play with it a little more.

**Comment by UglinessInTheUI** [comment] 2019-02-17 05:10
After saving the file and reloading it I'm getting a completely different result. Seems to be a bug.

**Comment by UglinessInTheUI** [comment] 2019-02-17 05:15
I can't fix it because it's not saving any of my changes. It's saving something but not 100%.

**Comment by BluePrintRandom** [comment] 2019-02-17 05:25
This is from bad memory alignment,

Append everything to a new blend usually fixes it.

**Comment by UglinessInTheUI** [comment] 2019-02-17 05:27
Here is the result. At first it worked great but after saving and reloading it got all messed up. Check it out.

[MyStartupFixed.zip](https://github.com/UPBGE/blender/files/2872683/MyStartupFixed.zip)

**Comment by BluePrintRandom** [comment] 2019-02-17 05:30
I am sorry but I am not downloading a massive .blend
I use upbge / bge and convert files all the time.

Start a new scene in upbge, delete everything.

Append the new stuff in from the old file to the new scene.

**Comment by UglinessInTheUI** [comment] 2019-02-17 05:34
It's less than a megabyte. The other scene was huge. 400+ MB. The one with the detailed house. I can't append anything from the old file because i reconstructed the player character from scratch and the Mouse Look actuator is not working. Lot's of stuttering and issues. So i tried to use the script which worked until i saved. After that nothing. It's all wrong transformations now.

**Comment by UglinessInTheUI** [comment] 2019-02-17 05:48
This is the script i tried which worked fine at first. After i saved and reloaded the scene it got all messed up. It's all wrong transformations now. Same script. Which worked fine at first.

import bge

def main(cont):
    own = cont.owner
    obj = cont.owner
    cam = bge.logic.getCurrentScene().active_camera
    mouse = bge.logic.mouse
    width = bge.render.getWindowWidth()
    height = bge.render.getWindowHeight()
    pos = mouse.position       
    xPos = pos[0] - (width/2) / width
    yPos = pos[1] - (height/2) / height
    bge.render.setMousePosition(int(width/2), int(height/2))
    obj.applyRotation((0,0,-xPos),1)
    cam.applyRotation((-yPos,0,0),1)
    bge.render.showMouse(0)

**Comment by UglinessInTheUI** [comment] 2019-02-17 05:53
The first 2 lines are duplicates. That's wrong. 

own = cont.owner
obj = cont.owner

**Comment by BluePrintRandom** [comment] 2019-02-17 05:54
.....
I think you need to take a look at local space
-z if forward on cameras, you actors forward is likely y+ or x+

Just align a empty to match you physics cores orientation
And stick the camera to the empty.

Rot = core.worldOrientation.to_euler()
Rot.y += offset
Empty.worldOrientation = Rot

#or rot.y or whatever

**Comment by UglinessInTheUI** [comment] 2019-02-17 05:59
OK let me try doing it with a script and two actuators first.

**Comment by UglinessInTheUI** [comment] 2019-02-17 06:06
OK now this version with 2 actuators works just fine but the fps is half of that from 2.79b.

[MyStartupA1.zip](https://github.com/UPBGE/blender/files/2872706/MyStartupA1.zip)

**Comment by UglinessInTheUI** [comment] 2019-02-17 13:07
Mouse Look Actuator doesn't work properly when Scene FPS is set to 10,000 and Refresh Rate is set to 2000 and V-sync is set to OFF. I built the latest source code and the problem is really there.

**Comment by EndSSgamesStudio** [comment] 2019-02-17 20:03
@BluePrintRandom The problem is also happening with the "startup" standard of UPBGE

I think I should create a Pull to replace...

**Comment by UglinessInTheUI** [comment] 2019-02-18 02:01
I created a new scene , added a cube , then added the Mouse Look Actuator on the cube and it worked again but it crashed as soon as i assigned one of the existing materials.

**Comment by UglinessInTheUI** [comment] 2019-02-18 03:42
Then i tried to open your blend file with a debug version of UPBGE and it crashed. 

![2019 02 17-20 38](https://user-images.githubusercontent.com/12206146/52926779-781baf00-32f4-11e9-8510-ec3953e105a9.png)

**Comment by UglinessInTheUI** [comment] 2019-02-20 15:19
Do you guys know where do i find the "Services" in the C++ source code ? I want to check for bugs and a few other things but i can't locate the "Services" anywhere in the code.

**Comment by UglinessInTheUI** [comment] 2019-02-20 15:43
When i run your file with the Release version of UPBGE it gives the following error in the console:


Read blend: C:\Users\Lindows\Downloads\MyStartup.blend
ModuleNotFoundError: No module named 'module'
Error: Failed to import the module 'module'

Blender Game Engine Started
Blender Game Engine Finished


The Debug version is not even able to open your blend because it's crashing.

**Comment by EndSSgamesStudio** [comment] 2019-02-21 12:57
@UglinessInTheUI 

> When i run your file with the Release version of UPBGE it gives the following error in the console:
> 
> Read blend: C:\Users\Lindows\Downloads\MyStartup.blend
> ModuleNotFoundError: No module named 'module'
> Error: Failed to import the module 'module'
> Error: totblock: 1
> 
> Blender Game Engine Started
> Blender Game Engine Finished
> 
> The Debug version is not even able to open your blend because it's crashing.

@UglinessInTheUI This error usually happens by the component.
the UPBGE initialization file contains a component with nothing.

**Remove and the problem will disappear.**
![screenshot_20190221095456](https://user-images.githubusercontent.com/35436445/53170489-f7dc9e80-35be-11e9-89af-50169951babc.png)

**Comment by BluePrintRandom** [comment] 2019-11-12 22:14
I am pretty sure this was an issue with a corrupt .blend

can I close this now?

**Comment by lordloki** [comment] 2020-04-25 16:42
It worked perfectly in 0.2.5 and 0.3.
Closing now. Thanks for reporting

**Closed by lordloki** 2020-04-25 16:42 UTC
