### ISSUE TITLE
in the latest version alpha 3.0 when i delete something it crash

### ISSUE THREAD

**Issue by devilspringtrap** [UPBGE/upbge#1146] opened 2020-03-14 10:12 UTC

**Comment by youle31** [comment] 2020-03-14 12:26
I can't reproduce the bug in several of my test files. Without more infos provided, the report will be closed in 1 day. Thanks for comprehension, we want to keep the tracker clean

**Comment by devilspringtrap** [comment] 2020-03-14 12:29
> I can't reproduce the bug in several of my test files. Without more infos provided, the report will be closed in 1 day. Thanks for comprehension, we want to keep the tracker clean

WHAT I AM NOT FREAKING TRACKER LOL

**Comment by youle31** [comment] 2020-03-14 12:32
The bug tracker. I'll close that right now.
If you want to report a bug, please follow this guide: https://github.com/UPBGE/upbge/wiki/Report-a-bug-guide

**Closed by youle31** 2020-03-14 12:32 UTC

**Comment by LP-ita** [comment] 2020-03-14 13:25
I had the same problem, in my case caused by an incompatibility with the "logic nodes" add-on...
