### ISSUE TITLE
TrackTo not working with appended files

### ISSUE THREAD

**Issue by ThiagoMoraesGD** [UPBGE/upbge#1797] opened 2023-02-16 18:38 UTC
Edit object actuator stop working when the object is appended from another file.

[test-trackto.zip](https://github.com/UPBGE/upbge/files/10759383/test-trackto.zip)

**Comment by youle31** [comment] 2023-02-17 12:24
it works if you convert first Cube.001 then Cube:

![Capture](https://user-images.githubusercontent.com/10052509/219650420-2f6f3e1a-c49d-4929-8808-d8bad5e3e578.PNG)

It is an expected behaviour since for now, we can only convert objects 1 after 1 (Not like in normal BlenderDataConversion where all KX_GameObject are available near the beginnning and that relationships between objects can be created because the whole gameobject list is available).

It's a known limitation and it's a bit similar to https://github.com/UPBGE/upbge/issues/1716 . (An option for later would eventually be to make it possible to convert instance collections after runtime beginning). I close this as it is similar to other report and that I added the reference to the report in this one.

**Closed by youle31** 2023-02-17 12:24 UTC
