### ISSUE TITLE
LibLoad(async) crash with AMD

### ISSUE THREAD

**Issue by Frostie2** [UPBGE/upbge#523] opened 2017-07-02 19:33 UTC
UPBGE crashes when using **async** with an AMD graphics card in the LibLoad function:
`bge.logic.LibLoad("file.blend, "Scene", async=True)`

**Comment by panzergame** [comment] 2017-07-03 09:39
Please provide us more information: which OS, which file, what said the console ? And over all you specified AMD GPU because you tested with an other GPU without any issue ?

**Comment by Frostie2** [comment] 2017-07-03 18:52
My Information:
-	AMD Radeon R7 200 Series grapihcs Card
-	Windows 10 (rs2_release 15063) (64 bit)
-	CPU: AMD A8-6600K APU with Radeon™ HD Graphics

The console said:
`Error: EXCEPTION_ACCESS_VIOLATION`
Then UPBGE ends itself.

Test file: https://www.dropbox.com/s/zs7yhnexwmb0t8r/libLoadTesting.zip?dl=0

In Blender 2.78c from blender.org, it just causes an interruption of the game, UPBGE crashes.
I tested it on a NVIDIA craphics card (NVIDIA GeForce 920M) and it works perfectly, even in 2.78c. Another 2 users tested it: AMD: Crash, NVIDIA: works

**Comment by panzergame** [comment] 2017-07-03 19:24
I like much more this bug report, thanks.

**Comment by Akira1San** [comment] 2017-07-03 20:25
Ive tested it too. Crash too. R 7 200 series video.

**Comment by panzergame** [comment] 2017-08-10 07:15
@Frostie2, @Akira1San : Could you confirm if you have the same issue in #553 ?

**Comment by Frostie2** [comment] 2017-09-10 16:59
Yes, I have the same issue. UPBGE closes immediately.

**Comment by Akira1San** [comment] 2017-09-10 18:10
Yep, open loader.blend and p key = crash in master build.

**Comment by youle31** [comment] 2017-09-10 19:27
I can't reproduce the issue

**Comment by Frostie2** [comment] 2017-09-18 20:03
The issue should appear with an AMD graphics card

**Comment by vlad1777d** [comment] 2018-10-27 16:07
Not only with AMD.

I have laptop:
Linux Mint 19 x64 Cinnamon
CPU: i5 5200u
GPU: Nvidia Geforce GT 840

I'm doing any LibLoad with async key == True - it crashes with `core dumped` error.

Can somebody check / confirm this ?

**Comment by vlad1777d** [comment] 2018-10-27 16:09
![screenshot from 2018-10-27 19-08-26](https://user-images.githubusercontent.com/12682937/47606393-c80bf880-da1b-11e8-9e7e-ffe5e67aebda.png)
![screenshot from 2018-10-27 19-08-46](https://user-images.githubusercontent.com/12682937/47606394-c8a48f00-da1b-11e8-9789-cdbda4752f33.png)

**Comment by BluePrintRandom** [comment] 2018-10-27 16:14
it appears you are on 0.2.3  -

0.2.4 has fixes for libload - can you test?

**Comment by vlad1777d** [comment] 2018-10-27 16:16
@BluePrintRandom , Sorry, I didn't noticed it already came out.
One moment, I'll test =)

**Comment by lordloki** [comment] 2018-10-27 16:37
Take into account that 'async' word now is 'asynchronous'

**Comment by vlad1777d** [comment] 2018-10-27 16:49
Thank you very much.
I can't figure out why do I have:
`/home/vlad/Programs/3d/upbge-0.2.4/blender: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory`
 error. 
Can somebody suggest something to solve it ?

**Comment by lordloki** [comment] 2018-10-27 16:56
Could you install tbb library?

**Comment by vlad1777d** [comment] 2018-10-27 17:13
@lordloki , aha, yes, I can.
I think that it would be better to bundle libraries, not to install additional dependencies into system.

I'll try to do this now.

**Comment by vlad1777d** [comment] 2018-10-27 17:37
I have the same error with 0.2.4 UPBGE.
[run.crash.txt](https://github.com/UPBGE/blender/files/2522030/run.crash.txt)
![screenshot from 2018-10-27 20-35-39](https://user-images.githubusercontent.com/12682937/47607388-10311800-da28-11e8-866b-c6afadb7ef79.png)
![screenshot from 2018-10-27 20-35-46](https://user-images.githubusercontent.com/12682937/47607389-10311800-da28-11e8-924b-d14ba5c85b00.png)

**Comment by lordloki** [comment] 2018-10-27 17:50
Do you have a repository where get the blend to debug them?

**Comment by vlad1777d** [comment] 2018-10-27 17:53
@lordloki , I have not, but I can create .zip file and share it via file changing service.

Would it be appropriate way for you ?

**Comment by vlad1777d** [comment] 2018-10-27 22:43
@lordloki , thank you very much for testing.

Strange. Seems, my drivers are not outdated.
I didn't updated kernel to last one, and I have to update xorg. 
But NVIDIA drivers, seems, work well.

The most strange thing is that it loads synchronously with success, but crashes only in asynchronous mode.

If you'll need my machine to perform some tests - I can share it with you via TeamViewer.
![screenshot from 2018-10-28 01-40-39](https://user-images.githubusercontent.com/12682937/47609983-d6c1d200-da52-11e8-90de-6565f68ffefa.png)

**Comment by lordloki** [comment] 2018-10-28 11:28
I'm trying to setup my linux development system to check there. If i dont have any results i will ask you for teamviewer help.
Thanks

**Comment by vlad1777d** [comment] 2018-10-29 02:52
Heh, tried to LibLoad my character after LibLoading scene, now it crashes even in synchronous mode =)
[run.crash.txt](https://github.com/UPBGE/blender/files/2523597/run.crash.txt)

**Comment by lordloki** [comment] 2018-10-29 05:08
This last crash comes from a softbody element

**Comment by vlad1777d** [comment] 2018-10-29 06:09
And can softbody elements be loaded via LibLoad ?
(or I did something wrong)

**Comment by panzergame** [comment] 2018-10-29 13:15
"I think that it would be better to bundle libraries, not to install additional dependencies into system"

It is not recommended to have a static tbb library and so use the system one : 

> Is there a version of TBB that provides statically linked libraries?

>  
> 
> TBB is not provided as a statically linked library, for the following reasons*:
> 
> Most libraries operate locally. For example, an Intel(R) MKL FFT transforms an array. It is irrelevant how many copies of the FFT there are. Multiple copies and versions can coexist without difficulty. But some libraries control program-wide resources, such as memory and processors. For example, garbage collectors control memory allocation across a program. Analogously, TBB controls scheduling of tasks across a program. To do their job effectively, each of these must be a singleton; that is, have a sole instance that can coordinate activities across the entire program. Allowing k instances of the TBB scheduler in a single program would cause there to be k times as many software threads as hardware threads. The program would operate inefficiently, because the machine would be oversubscribed by a factor of k, causing more context switching, cache contention, and memory consumption. Furthermore, TBB's efficient support for nested parallelism would be negated when nested parallelism arose from nested invocations of distinct schedulers.
> 
> The most practical solution for creating a program-wide singleton is a dynamic shared library that contains the singleton. Of course if the schedulers could cooperate, we would not need a singleton. But that cooperation requires a centralized agent to communicate through; that is, a singleton!
> 
> Our decision to omit a statically linkable version of TBB was strongly influenced by our OpenMP experience. Like TBB, OpenMP also tries to schedule across a program. A static version of the OpenMP run-time was once provided, and it has been a constant source of problems arising from duplicate schedulers. We think it best not to repeat that history. As an indirect proof of the validity of these considerations, we could point to the fact that Microsoft Visual C++ only provides OpenMP support via dynamic libraries.

https://www.threadingbuildingblocks.org/faq/11

I added a small note in the download site for linux distributions.

**Comment by lordloki** [comment] 2020-07-11 17:41
Fixed in last 0.2.5 branch. Check with this build https://mega.nz/file/thsiHIKC#VgLYdg2yaJWSr1JAi70asKAOzrrE8AeU6q8yDtuDw0A

Thanks for reporting

**Closed by lordloki** 2020-07-11 17:41 UTC
