### ISSUE TITLE
Anti Aliasing X16 in Game

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/upbge#988] opened 2019-01-14 03:41 UTC
I was testing the new features as soon as @lordloki solved the Compile errors
and I noticed that the Anti Aliasing x16 feature causes black screen.

Thanks!

![screenshot_20190114012918](https://user-images.githubusercontent.com/35436445/51095644-6ac35000-179d-11e9-8935-6cbee26d0b18.png)

**Comment by youle31** [comment] 2019-01-14 07:00
I can't reproduce the issue on my computer

**Comment by joelgomes1994** [comment] 2019-01-14 10:51
I confirm, not only for x16, but for x8 as well. x0, x2 and x4 values are working.
Latest master from 13/01/2019, UPBGE 0.2.4 x64 for Windows.

**Comment by RomStef** [comment] 2019-01-14 12:10
I have alredy compiled the last master of upbge and i can't reproduce the bug.
![immagine](https://user-images.githubusercontent.com/20901566/51111843-ba396880-17fd-11e9-9f41-95e48c233fb8.jpg)

**Comment by lordloki** [comment] 2019-01-14 12:34
Could you say me which graphic card you have each one?
Maybe it is specific of one brand  or similar....

**Comment by joelgomes1994** [comment] 2019-01-14 12:49
> Could you say me which graphic card you have each one?
> Maybe it is specific of one brand or similar....

![image](https://user-images.githubusercontent.com/19820741/51113688-f95dbe80-17e9-11e9-9f71-52a1188fead8.png)

**Comment by lordloki** [comment] 2019-01-14 13:07
It seems that the Intel HD 3000 only supports MSAA 2x and 4x samples.
https://forums.intel.com/s/question/0D50P00004908zPSAQ/hd-4000-and-antialiasing-?language=en_US

**Comment by lordloki** [comment] 2019-01-14 19:21
In my case with Nvidia 940m card it works ok for all levels.
For my Intel HD 5500 it fails with 16x level.
Surely, It works with 2x and 4x with almost all graphics cards. From there, it will work depending on the card or driver installed.

**Comment by EndSSgamesStudio** [comment] 2019-01-15 03:42
@lordloki 

Recently My video card gave Defect
so I'm using the Intel HD 5500


I can use 16x normally in the Previous Master

![screenshot_20190115013536](https://user-images.githubusercontent.com/35436445/51157224-091ae880-1866-11e9-94c7-48c779899171.png)

**Comment by Cotaks** [comment] 2019-01-16 15:44
16 and 8x not working on amd either

system used:
ryzen 5 1600
rx 470 nitro+ OC 4 GB
16Gb ram

the error at 16x: (.blend with only a cube, cube wil not show up)
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'

At 8x cube won't show up either, but also no errors.

BFBGE had the issue that 16X did not work and console would tell me that it has set it to 8x. But in UPBGE 16x gives error and 8x, 4x and 2x no error, but all not showing the cube. (standalone desktop/fullscreen checked)

in the embedded player all options works and again only 16x gives the above error, but cube is showing.

**Comment by youle31** [comment] 2019-01-16 16:44
Possibly related to https://github.com/UPBGE/blender/commit/23183936242afafaecd8a00a116668fa68e8381c

**Comment by Cotaks** [comment] 2019-01-16 17:17
Ok tested a few things, the not showing up was an driver issue, installed latest beta and it shows up.

but still have that gpuframebuffer error: 
<details>
<summary>Console output</summary>

```
Info: Total files 0 | Changed 0 | Failed 0
RNA_boolean_get: WM_OT_save_as_mainfile.exit not found.
found bundled python: D:\_upbge\2.79\python
Win32 Error# (0): De bewerking is voltooid.
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 96000hz instead
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: Radeon (TM) RX 470 Graphics
GL_VERSION: 4.6.13544 Compatibility Profile Context 25.20.15011.1004
GL_SHADING_LANGUAGE_VERSION: 4.60
Supported Extensions...
 GL_ARB_shader_objects supported?       yes.
 GL_ARB_geometry_shader4 supported?     yes.
 GL_ARB_vertex_shader supported?        yes.
 ----------Details----------
  Max uniform components.16384
  Max varying floats.128
  Max vertex texture units.32
  Max vertex attribs.29
  Max combined texture units.160

 GL_ARB_fragment_shader supported?      yes.
 ----------Details----------
  Max uniform components.16384

 GL_ARB_texture_cube_map supported?     yes.
 ----------Details----------
  Max cubemap size.16384

 GL_ARB_multitexture supported?         yes.
 ----------Details----------
  Max texture units available.  8

 GL_ARB_texture_env_combine supported?  yes.
 GL_ARB_texture_non_power_of_two supported?  yes.
 GL_ARB_draw_instanced supported?  yes.
Error: totblock: 1
Info: Total files 0 | Changed 0 | Failed 0
RNA_boolean_get: WM_OT_save_as_mainfile.exit not found.
found bundled python: D:\_upbge\2.79\python
Win32 Error# (0): De bewerking is voltooid.
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 96000hz instead
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: Radeon (TM) RX 470 Graphics
GL_VERSION: 4.6.13544 Compatibility Profile Context 25.20.15011.1004
GL_SHADING_LANGUAGE_VERSION: 4.60
Supported Extensions...
 GL_ARB_shader_objects supported?       yes.
 GL_ARB_geometry_shader4 supported?     yes.
 GL_ARB_vertex_shader supported?        yes.
 ----------Details----------
  Max uniform components.16384
  Max varying floats.128
  Max vertex texture units.32
  Max vertex attribs.29
  Max combined texture units.160

 GL_ARB_fragment_shader supported?      yes.
 ----------Details----------
  Max uniform components.16384

 GL_ARB_texture_cube_map supported?     yes.
 ----------Details----------
  Max cubemap size.16384

 GL_ARB_multitexture supported?         yes.
 ----------Details----------
  Max texture units available.  8

 GL_ARB_texture_env_combine supported?  yes.
 GL_ARB_texture_non_power_of_two supported?  yes.
 GL_ARB_draw_instanced supported?  yes.
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
Error: totblock: 1

```
</details>

**Comment by lordloki** [comment] 2019-01-16 20:24
Just for developer info. 
RAS_ICanvas has height = 1 and width = 1 at creation. 
Is this normal or should be equal to the height and width of OffScreen? OffScreen has the correct width and height of the viewport.

**Comment by youle31** [comment] 2019-01-17 00:50
I think it's ok as m_area seems to be initialized before UpdateOffScreens is called (GetWidth() return m_area.width and GetHeight m_area.height). This is initialized in KX_BlenderCanvas and GPG_Canvas constructors. I think I saw the same warning "Incomplete attachment" somewhere with my computer but i don't know if it is related to the current bug as Cotaks and me have this warning but this is working...

**Comment by lordloki** [comment] 2020-04-25 07:41
For 0.2.5 it works for me. Additionally, there is a new FXAA in the dropdown AA list.
Closing

**Closed by lordloki** 2020-04-25 07:41 UTC
