### ISSUE TITLE
Characters textures get messed up after using BGE deform in armature

### ISSUE THREAD

**Issue by LAPIDE** [UPBGE/upbge#699] opened 2018-05-26 01:34 UTC
Character textures are getting messed up when using BGE deform in armature (UPBGE 0.1.8)

And they are getting even more messed up using GPU hardware skinning made by @lordloki . 

here are prints on UPBGE 0.1.8 

![image](https://user-images.githubusercontent.com/20987945/40571219-5d58018e-606b-11e8-9bb8-418d434bd9da.png)

![image](https://user-images.githubusercontent.com/20987945/40571220-6908e32c-606b-11e8-9f58-cbf3710dc086.png)

here are prints on gpu hardware skinning : 

![image](https://user-images.githubusercontent.com/20987945/40571229-a539d900-606b-11e8-9e96-b3733213229e.png)

tried using one material in the mesh and multiple materials, it's the same. The characters use 152 bones, but is that a possible root for the problem?

**Comment by panzergame** [comment] 2018-05-26 09:19
Please provide an example file. Also GPU hardware skinning branch isn't maintained currently.

**Comment by lordloki** [comment] 2018-05-26 22:19
I think that you are using the build I uploaded in blenderartists. That build it has support for one material per mesh. Additionally, it is based in old BGE code and it doesn't apply to current UPBGE sources.

**Comment by LAPIDE** [comment] 2018-05-27 16:33
here's the file. Yes I have used a version in blender artists. but the upbge version of BGE deform also gets weird.

https://1drv.ms/u/s!AvNZsnuM-qg8ndwqdKNDQ1Wd9T4WaA

**Comment by panzergame** [comment] 2018-05-27 19:08
@LAPIDE : Could you check with a recent version if the bug was solved by 351f778 ?

**Comment by panzergame** [comment] 2018-07-03 20:35
@LAPIDE : I close the issue, reopen if the problem is still here, but I would had preferred a test from you earlier.

**Comment by artutava** [comment] 2018-07-10 07:14
@panzergame Hey, I had to travel so I did not have time to test it. Now I have tested it and it seems to be worse. I have tested with one material too. Tested with last build.
![image](https://user-images.githubusercontent.com/32049791/42494839-bfefb88c-83f7-11e8-87e0-d37987d22714.png)

**Comment by panzergame** [comment] 2018-07-18 21:30
@LAPIDE : Did you changed the file targeted by your link ? I have no texture from both blender and UPBGE (in editor).

**Comment by artutava** [comment] 2018-07-18 23:34
here's another one with textures

https://1drv.ms/u/s!AvNZsnuM-qg8nuUn6objtECVOONW5A

**Comment by artutava** [comment] 2018-07-25 13:29
Head renders fine here. But if you look at arms in body mesh and clothes. It gets a weird black shadow.

**Comment by panzergame** [comment] 2018-07-25 15:49
On 185163905c8a8e0be96261aabd04f5c19e87e50e:

![screenshot_20180725_194459](https://user-images.githubusercontent.com/8046004/43211921-036e5ee6-9033-11e8-9205-f4cedd6dd5cd.png)
![screenshot_20180725_194524](https://user-images.githubusercontent.com/8046004/43211922-0394a344-9033-11e8-9807-a79692f75d4a.png)
![screenshot_20180725_194548](https://user-images.githubusercontent.com/8046004/43211924-03b4a4e6-9033-11e8-83bf-adbb2bd414c4.png)
![screenshot_20180725_194608](https://user-images.githubusercontent.com/8046004/43211925-03d3887a-9033-11e8-9b53-3322ad31ca2f.png)


What is your GPU and OpenGL version ?

**Comment by artutava** [comment] 2018-07-25 16:39
Idk my open gl version. Had to travel for some days. But i have a gtx 970.

**Comment by LAPIDE** [comment] 2018-08-15 10:52
Now I am home. my gpu has open gl 4.6

**Comment by panzergame** [comment] 2018-09-10 18:58
Tested on b5ae73243c459db567a3ef048743571241558db4 still working for me. Could you display the log of blenderplayer ? (the one with OpenGL information)

**Comment by panzergame** [comment] 2018-09-24 13:35
@youle31, @lordloki : Are you able to reproduce or not the issue on windows ?

**Comment by youle31** [comment] 2018-09-25 14:45
Rodney displays fine for me in last master:

![capture](https://user-images.githubusercontent.com/10052509/46022194-70a7ff00-c0e2-11e8-92a7-a65359cf76ba.PNG)

**Comment by lordloki** [comment] 2018-10-05 04:34
With this file I get a crash at runtime. vR1 & vR2 without initializing
![image](https://user-images.githubusercontent.com/1015605/46516194-a7abac80-c868-11e8-86c6-b6cb546f85d4.png)

**Comment by lordloki** [comment] 2018-10-14 15:08
With lastest master it works OK to me:
![image](https://user-images.githubusercontent.com/1015605/46918563-bfef9a00-cfd3-11e8-89b5-ec67045805e6.png)

**Comment by lordloki** [comment] 2020-12-21 08:58
Closing this as it already worked.

**Closed by lordloki** 2020-12-21 08:58 UTC
Labels: bug
