### ISSUE TITLE
0.3.0 Stability issue

### ISSUE THREAD

**Issue by GBEY0402** [UPBGE/upbge#1220] opened 2020-06-07 19:20 UTC
Happened several times that the app closed without error message randomly while editing a mesh. PC's ressources are just fine, it runs on a i5, 10gb ram and 250gb ssd. Blender 2.79b never did.

**Comment by BluePrintRandom** [comment] 2020-06-07 23:38
what is your GPU?

**Comment by GBEY0402** [comment] 2020-06-08 01:11
I got a nvidia 650 1gb vram

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by GBEY0402** [comment] 2020-06-08 12:14
> what is your GPU?
> 
> also I sometimes have crashes if I have a object with alpha transparency selected on engine quit
> I think it's the 'outline shader' actually crashing

My mesh is plain, no texture applied yet,

**Comment by youle31** [comment] 2020-06-09 06:50
hi, we can do nothing without more informations.

At this point of development, most of stabilities issues may be related to viewport stability itself...  Some bugs can appear on some hardwares, often just after blender releases. 2.83 has been released, and just after, there was a complete eevee's materials refactor. I can't be sure that the problem is related to that, but such refactors can cause unstabilities which are fixed by blender developers some time after the refactors according to the bugs reports they have.

You can maybe find a build which is more stable for you in the builds done near may 15th (in lordloki builds in the mega folder)

Anyway, I close this report as we can't do anything without more informations provided.

**Closed by youle31** 2020-06-09 06:50 UTC

**Comment by GBEY0402** [comment] 2020-06-11 18:15
> hi, we can do nothing without more informations.
> 
> At this point of development, most of stabilities issues may be related to viewport stability itself... Some bugs can appear on some hardwares, often just after blender releases. 2.83 has been released, and just after, there was a complete eevee's materials refactor. I can't be sure that the problem is related to that, but such refactors can cause unstabilities which are fixed by blender developers some time after the refactors according to the bugs reports they have.
> 
> You can maybe find a build which is more stable for you in the builds done near may 15th (in lordloki builds in the mega folder)
> 
> Anyway, I close this report as we can't do anything without more informations provided.

i got the version of May, 17th and it works fine, ty
