### ISSUE TITLE
crash when clicking

### ISSUE THREAD

**Issue by mushroomeo** [UPBGE/upbge#1174] opened 2020-04-10 22:47 UTC
in latest UPBGE EEVEE i get now much more often instant quit blender when clicking in viewport. sometimes when after start but realized much more often when run BGE and then ESC and then click, it just quits.
had this after the fix from youle when you close BGE but it was actually "rare"...
its like completely random
tryed just now latest official 2.83 alpha and i seems cant get it

lordloki you lighting fast i just accidently pressed before write about problem enter and you replyed XD : ) THANKS

**Comment by lordloki** [comment] 2020-04-10 22:51
crash what when clicking what or where?

You need to have us more information. What UPBGE version, what day, how to reproduce the error. I mean, give us something to can work

**Comment by mushroomeo** [comment] 2020-04-10 23:03
in latest UPBGE EEVEE i get now much more often instant quit blender when clicking in viewport. sometimes when after start but realized much more often when run BGE and then ESC and then click, it just quits.
had this after the fix from youle when you close BGE but it was actually "rare"...
its like completely random
tryed just now latest official 2.83 alpha and i seems cant get it

lordloki you lightning fast i just accidently pressed anter before write about problem and you replyed XD : ) THANKS

**Comment by lordloki** [comment] 2020-04-10 23:23
Do you mean the build from today (2020/04/11)?
What is your graphics card?
Are you using windows, linux or macos?

In last build I can't make it to crash (I tested it starting/closing UPBGE more than 100 times and alternatively selecting objects, panel, lights, etc)

**Comment by mushroomeo** [comment] 2020-04-10 23:33
well had it from 4/10 but now downloaded latest and its still crashing.

i using win7 64bit

i sadly tryed many times doign same thing exactly but i cant reproduce it. i just open UPBGE and then first click on viewport click it crashed, sometimes later somwhen , but most times after i close BGE

**Comment by mushroomeo** [comment] 2020-04-10 23:53
okay thats crazy . now i just installed latest nvidia drivers and did complete new installation then restarted pc, and now if i start UPBGE and click on New material to add its always instantly crashes.
i want say that i had long time ago last year in UPBGE too many times realized that UPBGE crashed if clicked somewhere in material values, but it was rare and so didnt report : (

**Comment by mushroomeo** [comment] 2020-04-11 14:31
ôkay now just downloaded again latest UPBGE EEVEE and the material crash is no more!! thats super cool.

but the random crash if clicking is still there which makes unworkable since is too much...

**Comment by mushroomeo** [comment] 2020-04-11 18:38
okay i just reported it as bug because latest blender 2,83 alpha does crash too after open blender and click fast on cube. i really couldnt get this crash before in official blender. but i see that UPBGE always crashes if i click on object after i close BGE, if i just click on empty space then it does not crash after i close BGE.

**Comment by gogela** [comment] 2020-04-12 09:40
Not sure if it is related to the above, but I experienced similar behavior:
I gave a try the VM image - downloaded as CentOS7-VMWare-UPBGE-Enviroment.7z running it in VMware Workstation 15.5.2. When exiting player mode (activated by P, exited with Esc) the UPBGE environment crashes. The terminal output is pasted below.

```
Debug: 1606, 766
rcti: : xmin 0, xmax 1605, ymin 21, ymax 786 (1605x765)
found bundled python: /home/upbge/UPBGE/build_linux_full/bin/2.83/python

Blender Game Engine Started
context mismatch in svga_sampler_view_destroy
Blender Game Engine Finished
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
VMware: vmw_ioctl_command error Invalid argument.
Aborted (core dumped)


```

**Comment by lordloki** [comment] 2020-04-12 12:10
The crash with CentOS VM is totally normal due to the poor OpenGL support that the VM has. I have it too.

**Comment by mushroomeo** [comment] 2020-04-14 01:53
i did disable every addon and keymap and option in user preferences and compared to load factory settings but it still did crash. took me many hours  : (

now finaly fixed it. it looks like the userpref file was somehow corrupted and the load factory preferences settings fixed it in prefecenes. now it dont crash anymore. i super sorry for trying to help me.

i really was sure factory settings crashes too, maybe i didnt saved and restarted it because didnt wanted lose many hours setups... and now i see that load factory preferences is different than load factory settings... didnt even noticed

please close this issue
really sry guys

**Comment by lordloki** [comment] 2020-04-14 03:32
No need to be sorry. We are glad to help you.

Closing the issue now

**Closed by lordloki** 2020-04-14 03:32 UTC
