### ISSUE TITLE
Bug: Alpha sort slower in UPBGE than in Blender 2.78c

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/upbge#430] opened 2017-03-15 05:23 UTC
blend: http://pasteall.org/blend/index.php?id=45937
# **In the material tab, game setings switch to alpha sort.**

**Comment by DCubix** [comment] 2017-05-02 21:44
?

**Comment by Akira1San** [comment] 2017-05-02 23:39
I tested in 0.1.0 and 011, they give big performance while 012 gives less.
Can anyone else test?

**Comment by panzergame** [comment] 2017-05-03 19:26
I confirm the slow down, in 0.1.1 i have 0.75ms for the rasterizer whereas i have 1.21 in 0.1.2.

**Comment by panzergame** [comment] 2017-05-03 19:35
Commit : 5718bff90f5158a66dcc9f3255855d2c6e6ebd10

**Comment by panzergame** [comment] 2017-05-03 19:50
The issue is that we need to flush the index array of the sorted polygons every frame, this wasn't done before, anyway the way i designed it in 0.1.2 is not so good.
What i propose now is to replace:
```
	if (material->IsZSort() && rasty->GetDrawingMode() >= RAS_Rasterizer::RAS_SOLID) {
		m_mesh->SortPolygons(this, args.m_trans * MT_Transform(m_meshUser->GetMatrix()));
		m_displayArrayBucket->SetPolygonsModified(rasty);
	}
```

By:
```
	if (material->IsZSort() && rasty->GetDrawingMode() >= RAS_Rasterizer::RAS_SOLID) {
                int *index = m_displayArrayBucket->GetIndexMap()
		m_mesh->SortPolygons(this, args.m_trans * MT_Transform(m_meshUser->GetMatrix(), index));
		m_displayArrayBucket->FlushIndexMap();
	}
```

And use the glMap/UnmapBuffer function to avoid extra copy of the indices.

**Comment by Akira1San** [comment] 2017-05-23 21:52
The latest master build give some more frame drop with alpha sort: 
upbge 017 -200fps, master build 120fps
Ive done a bisect and it leads to the commit: UPBGE: Use VBO index buffer for polygon sort.
8e2a271c587466580bc13bfe7eb65424f906b672
Blend file to test:   http://pasteall.org/blend/index.php?id=46699

**Comment by youle31** [comment] 2017-05-23 22:55
Akira_san: You're sure that it is the right test file? I see no alpha in this file.
Anyway, I confirm that I have better performances before the commit you mention than in the last master (1250 fps -> 1180)

**Comment by Akira1San** [comment] 2017-05-24 07:24
Ops, forgot to say to switch to alpha sort.

**Comment by youle31** [comment] 2017-05-24 12:49
I have not this issue with my computer. I have exactly the same result (I enabled alpha sort) at the commit you mention and at the commit before and I have the same performances in 0.1.7 and in last master... Maybe this is a problem related to ATI cards or your drivers... Maybe it could be related to this bug: https://github.com/UPBGE/blender/issues/494 which concerns the same commit... I don't know

**Comment by Akira1San** [comment] 2017-05-24 13:22
Ok im going to reinstall the win8, so gonna update the drv...
Made a test with the study room, the result is great! see image:
http://pasteall.org/pic/show.php?id=115839
Now with master, we have a double speed compared to the 017 :D
I only remove the modifiers and disabled the reflection script.

**Comment by youle31** [comment] 2017-05-24 20:02
First bad commit: https://github.com/UPBGE/blender/commit/a147c7e7082548792b664ed7122fd0f619e2113c

(before 900 fps, after 300 fps)

**Comment by panzergame** [comment] 2017-07-18 22:25
@Akira1San : Could you test with latest master please ?

**Comment by Akira1San** [comment] 2017-07-19 05:27
Tested, the same low fps.

**Comment by youle31** [comment] 2017-08-06 00:39
About this issue, I did tests in last master.
I have 500 fps with the test file. I remarked that the issue came from storage->GetIndexMap() called each frame.

So do you think we can cache the buffer returned by GetIndexMap() ?

When I cache the buffer in the test file I have 1000+ fps

**Comment by Akira1San** [comment] 2017-08-06 13:16
Made a test: http://pasteall.org/pic/index.php?id=117793

Looks great, even fixed the lamp slow down as can be seen from the images(I mean when switching the hemp to point) However, theres still a regression as can be seen, compared to bf bge. I think, that regression comes after .010 version.

**Comment by youle31** [comment] 2017-08-06 18:16
In fact I don't know in what case alpha sort option is used, I don't have good test files in my files so I can't tell if I don't break the feature with the branch I pushed. This was just to show the impact on performances of GetIndexMap.

@Akira_san: In the image you shared, the shading looks not the same in BF bge/upbge. Is this normal?

Else is there is still a performance difference this can also be explained with NodeUpdateGS called each frame for ApplyRotation in the code.

**Comment by Akira1San** [comment] 2017-08-06 21:06
I see.
The difference of light is from changing the lamp from hemi to point.

**Comment by panzergame** [comment] 2018-10-14 10:40
The vertex memory model was changed in 0.2.4 and many modifications happened.

I retested with this file: 
[ge_mesh_sort_test.zip](https://github.com/UPBGE/blender/files/2476277/ge_mesh_sort_test.zip)

I get for UPBGE 0.2.4 (086255edf5c8abbf298a92d95fde71b4c4e79452) 26.0ms for rasterizer,
for blender 37.5ms.

**Comment by panzergame** [comment] 2018-10-20 16:09
@Akira1San, @youle31 : Can you confirm the test please ?

**Comment by youle31** [comment] 2018-10-20 19:39
I have these results in BF master and upbge master:

BF:
![bf master](https://user-images.githubusercontent.com/10052509/47259854-9a213400-d4b0-11e8-8f07-0a22d8f72dbd.jpg)

upbge:
![master](https://user-images.githubusercontent.com/10052509/47259859-a2796f00-d4b0-11e8-9325-a71f33d5e48e.jpg)

**Comment by Akira1San** [comment] 2018-10-20 19:51
heres my test; image 023 - 024: http://pasteall.org/pic/f730f61d5b7931c55a4be51e61a45dab
In bf bge it shows better result. - pic bf bge: http://pasteall.org/pic/167cba229ccef184efb46f1ce2f67e9a

**Comment by lordloki** [comment] 2021-12-11 11:00
Now we use eevee directly in 0.3. Closing the issue.
Thanks for the feedback

**Closed by lordloki** 2021-12-11 11:00 UTC
Labels: bug
