### ISSUE TITLE
UPBGE 0.2.5 Crash when using the first option of UV UNwrap menu

### ISSUE THREAD

**Issue by firefoxjco** [UPBGE/upbge#1200] opened 2020-04-29 15:59 UTC
When I try to use the first option of the Unwrap menu in the standard plan and in the suzane, UPBGE 0.2.5 closes automatically.
My system: Win 7 64 bits.
PS .: In the 32bits version it does not crash when using the mentioned Unwvrap function

**Comment by lordloki** [comment] 2020-04-29 16:30
I just checked and I have no crash for unwrap in win64 or win32
![image](https://user-images.githubusercontent.com/1015605/80620757-b0fdfa80-8a46-11ea-8f69-83c920400a6f.png)
If you could copy this file where your blender executable is, uncompressit, execute it, force to blender to crash and copy here the 2 resulting .txt files would be helpful

[blender_debug_log.zip](https://github.com/UPBGE/upbge/files/4552998/blender_debug_log.zip)

**Comment by BluePrintRandom** [comment] 2020-04-29 17:20
does this happen in current master?

2.9x is in bfcon1 so we may see some breakages temporarily

**Comment by lordloki** [comment] 2020-04-29 17:41
It is in 0.2.5

**Comment by BluePrintRandom** [comment] 2020-04-29 18:07
oh :D

**Comment by firefoxjco** [comment] 2020-04-30 15:35
Here are the files generated after the crash.


[debug_logs.zip](https://github.com/UPBGE/upbge/files/4559307/debug_logs.zip)

**Comment by youle31** [comment] 2020-05-01 15:50
I can't reproduce the crash, but having a look at the debug logs, i'm wondering if the crash can be related to color management settings.

Can you check that your colormanagement settings are the same than me?

![Capture](https://user-images.githubusercontent.com/10052509/80818646-e126d400-8bd3-11ea-8cd3-29d5f0c8f2e7.PNG)

I say that because in blender 2.79b, there was an issue with colormanagement. It was normally fixed in last 2.79 nightly build. But maybe AMD card still have some problems to set the correct settings?
If it is an issue related to colormanagement, maybe you will have to ensure each time that the color management settings are correctly set.

**Comment by firefoxjco** [comment] 2020-05-04 15:09
> I can't reproduce the crash, but having a look at the debug logs, i'm wondering if the crash can be related to color management settings.
> 
> Can you check that your colormanagement settings are the same than me?
> 
> ![Capture](https://user-images.githubusercontent.com/10052509/80818646-e126d400-8bd3-11ea-8cd3-29d5f0c8f2e7.PNG)
> 
> I say that because in blender 2.79b, there was an issue with colormanagement. It was normally fixed in last 2.79 nightly build. But maybe AMD card still have some problems to set the correct settings?
> If it is an issue related to colormanagement, maybe you will have to ensure each time that the color management settings are correctly set.

My color management settings are the same. But I suspect it has something to do with this system configuration (Intel Dual core and AMD RAdeon HD 6670 Graphics Card).
I tested it in my usual working configuration (Ryzen and AMD RTX 580 Graphics Card and it worked perfectly.
Strange that this crash only happens with the objects Plane and Suzane.
If you want to close this investigation request, feel free.

**Comment by lordloki** [comment] 2020-05-09 17:30
I was doing several tests in 4 computers with differents graphic cards and they worked. I close the report now but if the issue is affecting to someone, please feel free to open it again.

Thanks for reporting.

**Closed by lordloki** 2020-05-09 17:30 UTC
Labels: 0.2.5, Investigating, bug
