### ISSUE TITLE
Depth Transparency enabled material not showing in viewport and/or with AA samples

### ISSUE THREAD

**Issue by Wisaam** [UPBGE/upbge#673] opened 2018-02-02 18:24 UTC
I don't know if this problem is specific to my system or not, but whenever I enable depth transparency on a material, it becomes transparent in the viewport.
 Note: It does show up and works perfectly fine once I hit 'P' and the game starts.

Other than that, if I set the Anti-Aliasing samples to anything other than off, the object doesn't show up at all. Neither in the viewport nor after starting the game.

I am using 32-bit UPBGE 0.2.3 stable release on 64-bit windows 10 with the built-in Intel HD graphics 4000. The sample blend and system-info file is attached.

[system-info.txt](https://github.com/UPBGE/blender/files/1690348/system-info.txt)
[Blend File](https://drive.google.com/open?id=1Mm8UQeTCE4GqcG3FWOSzieWhWNdh5NeE)

**Comment by justinbarrett** [comment] 2018-02-03 07:08
My objects also turn invisible when setting this flag..I cannot attest to the rest though, as I do not use anti aliasing
...nvidia gtx650  linuxmint 18.3 64bit any version of upbge(64bit)

**Comment by panzergame** [comment] 2018-07-26 10:02
About the viewport, blender is not rendering to an off-screen which disallow the ability to send a depth texture to shaders. In future I will set a material without depth transparency in viewport and recompile it at game start with the option enabled.

> I also find the depth setting confusing, I'm not sure if it adjusts the distance of the falloff(transparency 
falloff) or the overall transparency etc...

It adjusts the influence of the depth from the object to the rest of the scene into the total transparency.
More the "plane" is near to other objects more the transparency increase.

@Wisaam : Is the issue related to multi-samples still actual with recent master ?

**Comment by justinbarrett** [comment] 2018-07-26 13:22
well since this posting I have played with it a bit more...it's still not very clear about the setting..but I have a feel for it now...
It is just difficult to adjust since it is not rendered until the game engine is running..I would not call this a show stopper...but it does not feel like it is operating as intended...or it is un-finished...I didn't open this ticket though and I can definitely deal with it.

**Comment by lordloki** [comment] 2020-05-17 01:47
This is a known "bug" and it won't be fixed in 0.2.5a. As in 0.3 we have not depth transparency I close this.

**Closed by lordloki** 2020-05-17 01:47 UTC
Labels: Open, bug, cannot be fixed
