### ISSUE TITLE
UPBGE Development ideas

### ISSUE THREAD

**Issue by youle31** [UPBGE/upbge#1136] opened 2020-03-04 08:34 UTC
- [ ] Add more builtin uniforms to 2D filters (projection matrix, viewmatrix, a noise texture?, eevee utilTex for ambient occlusion filters? (maybe needs to delay the end of DRW_game_render_loop to have the textures available when filters are rendered)).
- [ ] Add more 2D filter templates (Denoise, HBAO+...).
- [ ] Restore libload if someone is interested to work on it.
- [x] Implement smaa (I read a bit doc about it here: https://github.com/dmnsgn/glsl-smaa + lordloki branch.
- [x] Remove WorldIpo/Replace with world->nodetree actions.
- [x] Recover ObColor/Lights Ipos.
- [ ] Find why KX_GameObject.updatePhysicsShape sometimes needs several frames to update.
![Capture](https://user-images.githubusercontent.com/10052509/76154415-336bdd00-60dc-11ea-94e0-345367e3763e.PNG)
So this is not updatePhysicsShape the issue. This is that when you replace gfx, it needs several frames? Or when you add an object?

- [ ] Recover ReplaceMesh use GFX/use physics.
- [ ] LOD fade?
- [ ] Add Lerp to smooth mouseLook movements (does it already exists?)
- [ ] Create a "game workspace" like "modeling"/"sculpting"...
- [ ] Recover some upbge 0.1.9 to 0.2.4 commits ? See upbge 2.7 git log.
NOTE: We already are at UPBGE 0.2.0 level. (Thanks lordloki!)
- [x] Improve profile (remove some things from rasterizer and add it in other categories)

- [x] Clean up unused actuators.
- [x] Cleanup/reOrganize headers.... with source/tools.
- [x] Cleanup lights files/code.
- [x] Cleanup background code (zenith/horizon...deprecate...). Actually was already done i think
- [ ] Cleanup python API.
- [ ] Documentation (Thanks to lordloki for the work already done!).
- [ ] Adapt UPBGE/testfiles repository to upbge 0.3
- [ ] UPBGE Python console
- [ ] In physics tab, add an option to choose if we want to create the shape from evaluated mesh or original mesh.
- [x] In physics tab, remove invisible option as we can already have the object invisibled in object tab > display as wire
- [x] Disable old SoftBodies UI as they are not supported using blender meshes. The physics behaviour works but the meshes can't be deformed as the deformers code has been removed.
- [x] Restore python components templates
.............
List only editable by commiters, please.

**Comment by BluePrintRandom** [comment] 2020-03-04 17:28
I have 1 commit :D

but your list looks great.
only a few additions

1. investigate using cycles or rtx to get at ATAA

2. accelerate vertex skinning with a game optimized armature modifier

3. a new blend type for alpha for water 
render 1 time opaque (to get SSR) - render again alpha - (to get at refraction)
mix the two using Fresnel 

-blur pass on alpha hashed materials

**Comment by RomStef** [comment] 2020-03-06 15:38
I'm not a committer and i don't have enough experience for helping in development and upgrade upbge but i have searching how the other softwares manage the LOD Fade effect and the unity methods seems well documented if this can help

https://docs.unity3d.com/Manual/class-LODGroup.html

**Comment by RomStef** [comment] 2020-03-06 17:43
workspace UI proposal for game logic

![upbge_interface_proposal](https://user-images.githubusercontent.com/20901566/76108111-426a6680-5fda-11ea-9f46-5bb41e9582e6.jpg)

**Comment by youle31** [comment] 2020-03-06 23:24
I'd personally include the text editor in the opened things

**Comment by lordloki** [comment] 2020-04-17 18:43
I did this start blend mock-up
![image](https://user-images.githubusercontent.com/1015605/79603178-21725680-80ec-11ea-85cb-11c154f16373.png)

**Comment by lordloki** [comment] 2020-04-17 20:43
OK, I don't really how to activate eevee viewport shading to rendered from start. It always start in solid mode:
![image](https://user-images.githubusercontent.com/1015605/79612400-ea587100-80fc-11ea-9458-403f3dde1f2a.png)

**Comment by youle31** [comment] 2020-04-18 03:23
I like the first version without the file browser, but in solid mode. Else, I won't replace the point with a sun (but i don't really mind). I'm ok with the first version in solid mode.

**Comment by lordloki** [comment] 2020-04-25 13:47
Closing the issue to make it not visible from tracker list. As it is pinned this is not a problem as it is showed in Top part.

**Closed by lordloki** 2020-04-25 13:47 UTC
Labels: development ideas

**Comment by IzaZed** [comment] 2020-05-07 11:41
Concerning LibLoad, I get very low framerates and strange behaviour (some code not working, being applied at wrong times for example) when loading a file with the Game Actuator.

What would be the best way to completely jump to another .blend file at runtime?

**Comment by youle31** [comment] 2020-05-07 12:23
I tried to rework a bit on game actuator and we merged some work 13 days ago: https://github.com/UPBGE/upbge/pull/1191
@IzaZed : you can try with a more recent upbge 0.3 and if you have some bugs, you can report issues with the most simple test files you can (if possible without using logic nodes addon)

**Comment by IzaZed** [comment] 2020-05-07 13:43
It's good in recent builds 👍 
calling python LibLoad still results in an ACCESS VIOLATION, but I think that's a known one

**Comment by youle31** [comment] 2020-05-07 15:27
LibLoad has been replaced with scene.convertBlenderObject/scene.convertBlenderCollection, I won't work on it. If someone wants to work on it, the old code is still there but as we have convertBlenderObject/convertBlenderCollection and that we can use bpy.ops.wm.append or import_mesh_ply or import objects from different files types or another .blends then convert it into gameobjects, it seems to me that libload is not needed anymore. For Async, we'll maybe try to find something but with the new system (not with libload unless someone wants to put his hands in this extremely complex code).

**Comment by lordloki** [comment] 2020-05-07 17:24
I think import alembic is multithreading and asynchronous. I have to check it

**Comment by BluePrintRandom** [comment] 2020-05-07 19:03
another thing to consider - the new intel threaded container type should  help us potentially - maybe we can use it in a few places?

**Comment by UnidayStudio** [comment] 2020-05-17 15:31
Why not the same design that 0.2.5 have?

> OK, I don't really know how to activate eevee viewport shading to rendered from start. It always start in solid mode:
> ![image](https://user-images.githubusercontent.com/1015605/79612400-ea587100-80fc-11ea-9458-403f3dde1f2a.png)

Why not the same startup design that 0.2.5 have? Because it's already well known and tested. From my experience teaching upbge, more tabs opened by default may cause confusion for the very beginners. Thanks for your work! :)

**Comment by Trample-ingame** [comment] 2020-07-23 16:29
there will be a chance to have all deform modifiers working in UPBGE during the game? it would be a great help instead of animate all with armature and shape key which is a boring long procedure

**Comment by youle31** [comment] 2020-07-23 16:33
deform modifiers are working during runtime in upbge 0.3

**Comment by BluePrintRandom** [comment] 2020-07-23 17:16
could we make a way to overide the texture a modfier is using with another image buffer?

**Comment by Trample-ingame** [comment] 2020-07-23 20:21
youle31 i mean UPBGE not with blender and eevee
i tried today with cast, lattice, also displace, they keep the modified shape but don't animate during the playmode

**Comment by lordloki** [comment] 2020-07-23 21:32
Hi @Trample-ingame ,
Currently, we have not planned new development for Upbge 0.2.5. At this moment we will put several easier fixes on it but all the new development will go over Upbge 0.3.
This issue is a collection of ideas for 0.3.

**Comment by Trample-ingame** [comment] 2020-07-23 22:41
ah :( , so about 0.3 i want to say, i honestly think the old blender is more intuitive and blender internal /render was very fast to create materials with texture and set texture parameters at once in 10-20 seconds and get some very cool stuff, now in the new one i don't even know where to touch, if the property layout would had meant to be closer to the old blender it'd had be much easier to use it, i still don't understand why blender 2.8 it's like a now software with new icons that confusing me in search of tools, i tried sometime to use the new blender but i go back after 10 minutes, i want to switch to the new lite eevee render mode but it's like i have to learn a new software with scene and materials creation much longer with nodes :/ it's stressing, also i'm waiting to have 0.3 much more stable,
i don't know how easy it is but you could improve the conversion of materials and texture to cycle to reproduce the exact same effect i have in blender internal when for example i set normals, alpha, influence color and hardness to a single texture, i tried it and the result was horrible, at least i wouldn't have to rebuild all materials of my games, it would be so stressful

**Comment by BluePrintRandom** [comment] 2020-07-23 22:50
> ah :( , so about 0.3 i want to say, i honestly think the old blender is more intuitive and blender internal /render was very fast to create materials with texture and set texture parameters at once in 10-20 seconds and get some very cool stuff, now in the new one i don't even know where to touch, if the property layout would had meant to be closer to the old blender it'd had be much easier to use it, i still don't understand why blender 2.8 it's like a now software with new icons that confusing me in search of tools, i tried sometime to use the new blender but i go back after 10 minutes, i want to switch to the new lite eevee render mode but it's like i have to learn a new software with scene and materials creation much longer with nodes :/ it's stressing, also i'm waiting to have 0.3 much more stable,
> i don't know how easy it is but you could improve the conversion of materials and texture to cycle to reproduce the exact same effect i have in blender internal when for example i set normals, alpha, influence color and hardness to a single texture, i tried it and the result was horrible, at least i wouldn't have to rebuild all materials of my games, it would be so stressful

- I would finish your current projects in upbge <= 0.2.5  and then try playing with eevee,

it's actually very easy to use - the principled node can describe almost any material.
if you don't get hooked on it 0.2.5 repo exits if you want to do PR for it. (pull requests)

**Comment by juancarlospaco** [comment] 2021-10-04 01:23
Hello!; I am working on adding a new programming language to UPBGE, is already done (partially),
it can allow faster performance than Python, without too much effort from UPBGE core devs,
but I need someone to "test" the interoperability in UPBGE, and how it feels from gamedev POV,
it can be simple tiny examples, or unittests, but I do not have the UPBGE skills to do it.

All open source as MIT, requires no changes on UPBGE code, should be quick if you know UPBGE.

It should be faster than Python, GDscript and JavaScript code, simpler than C++ code.

If someone is interested ping me by mention or reply me...

**Comment by RadhaMadhavaDas** [comment] 2023-04-28 06:06
I'd like to see a UPBGE development fund, and dedicated paid team members, with a support team as a paid option to help users learn and troubleshoot the engine. There should be a marketplace for assets and prefabs, as well as promote games in development, as well as releases.

I can help with these things if I can find someone on the team who's willing to talk?

**Comment by sammtrend** [comment] 2024-01-25 09:36
Hi,
Not sure this is the right place to ask. 
I would like to know if this is possible to request new sensor. I would like to use loadcells from here :[https://www.phidgets.com/?prodid=229](https://www.phidgets.com/?prodid=229)
in combination with [https://www.phidgets.com/?prodid=1270](https://www.phidgets.com/?prodid=1270). There is an API for multiple coding languages (C, python,...). I can do testing as I have those devices with me. 
Samm

**Comment by Trample-ingame** [comment] 2024-01-25 17:31
you should ask it to the owner of the plugin not to me, i only created the
text/grid file

Il giorno gio 25 gen 2024 alle ore 10:36 sammtrend ***@***.***>
ha scritto:

**Comment by JYamihud** [comment] 2024-02-27 15:44
# Rendering
- [ ] Make motion blur button in the render settings do something in the game.
- [ ] Make Ambient Occlusions work in the game.
- [ ] Add Z-Depth and other buffer types into the live compositor, so mist could be created without falling back to volumetrics.
- [ ] Investigate making volumetrics with non-boxy shapes have their shapes visible in game.
- [ ] Investigate into Shader To RGB node so it could be used on Transparent Node to capture the image underneath. At the moment, the texture captured this way has black color with 0 opacity. It could be used for various effects like for ripples in the water. At the moment it is somewhat possible with Screen Space Refraction, but it is not ideal.

# Performace
- [ ] Investigate running **Depsgraph updates in a separate thread**. As far as I understand it is CPU based and runs before the rendering ( on the GPU ) which could instead by done in the same time ( because those two separate chips ). This could result in one frame delay. Basically the renderer will have to render the previously calculated frame, while the next one is being calculated by the Depsgraph. But since depsgraph takes about the same time as rendering ( at least in my case ) it could be very beneficial to have this delay option to improve performance significantly. See: https://github.com/UPBGE/upbge/issues/1877

# Stability
- [ ] Investigate **fixing jiggling at distances**. Apparently the coordinates of various geometry points are stored in such a way that reduces their precision the larger the number gets. I understand it like this: say there is a point at X being `0.00000001` but if you add a `10` to it it will be just `10.0` because the `00000001` will get cut out to make room for the number on the other side to save some memory. In this particular case is not that big of a deal. But when you go into very large numbers territory it becomes an issue. To demonstrate it, you can launch an object with very fast speed away from the center, with the camera parented to it. You will see that this object will start jiggling and at some point it will get quantized into a blocky mess. I think to fix it, we could instead of using World Center as the center, use the camera position as the center. Or at the very least, shift all objects so the camera will end up in the center, once a certain threshold is crossed.
- [ ] Fix the bug with full-screen messing up with screen settings, especially with multi-screen setups. 

# Physics
- [ ] Add option to read collision impact forces. There is a documented method for it, but it is not for Bullet Physics.

Vehicle Constraints:
- [ ] Add options to read applied forces on wheels.
- [ ] Add options to read resistances applied on wheels from other objects.
- [ ] Add options to read whether the wheel is touching the ground. Or what force is exerted on it's suspension.

**Comment by BluePrintRandom** [comment] 2024-03-28 21:27
I would recommend wrapping armature physics object using bt_multiBody, 

this can be used in conjunction with a 'target action armature' to attempt to match with the ridged body armature. 

@JYamihud - Multiple passes is already planned by composition team (AOV / Depth etc)
