### ISSUE TITLE
“UPBGE” is damaged and can’t be opened.

### ISSUE THREAD

**Issue by PlumpMath** [UPBGE/upbge#1591] opened 2021-12-05 00:50 UTC
x86_64 intel macOS version
UPBGE.app click error.
but, I can run this at the terminal.
/Applications/UPBGE.app/Contents/MacOS/Blender

I don't know what to do.
Thank you.

**Comment by lordloki** [comment] 2021-12-05 01:19
I just check in a MacOS Catalina (10.15.7) and it works. What MacOs version do you have?

https://user-images.githubusercontent.com/1015605/144729604-eb6bc2da-2da2-4069-9af9-7a3ea713e2ec.mp4

**Comment by PlumpMath** [comment] 2021-12-05 13:43
I use latest monterey.
I've had this happen before at big sur.

**Comment by serapth** [comment] 2021-12-06 00:08
+1, Monterey as well, M1 Max MBP.  Website and GitHub versions both give same error.

**Comment by TriVoxel** [comment] 2021-12-06 15:05
I am the maintainer of the macOS builds. @PlumpMath @serapth if you try to run the program and then head to System Preferences > Security & Privacy > General, do you see something asking you to run UPBGE anyways? This is a common issue with macOS.

**Comment by PlumpMath** [comment] 2021-12-06 15:39
@TriVoxel UPBGE does not appear.  So, experiment with other apps. Experiment with FreeCAD and it will come out.

**Comment by TriVoxel** [comment] 2021-12-06 16:58
@PlumpMath Okay I am very confident that I missed a step in the code signing process which is triggering the macOS Gatekeeper to  block the app entirely. This is the error we get when macOS is angry about code signing. Instead of saying something useful, Apple pretends the app is broken altogether to discourage users from running it. For now, just run UPBGE from Terminal with `UPBGE.app/contents/MacOS/Blender` and I will release patched builds that have the correct code signatures. Sorry for this inconvenience! 😬

**Comment by PlumpMath** [comment] 2021-12-06 18:33
I'm running it with your console.  thank you.  I'm a clojure developer, so blender upbge both don't like this part.  If this were possible, clojure developers like me would flock to upbge. 

https://github.com/clj-python/libpython-clj/issues/188

flock to UPBGE~~~~

**Comment by gramlin** [comment] 2021-12-06 20:30
> 

Tried that but no cigar. On BigSur.

**Comment by owdoo** [comment] 2021-12-06 23:08
Same problem here, running Monterey on an Apple Silicon MacBook Air (2020). No Security & Privacy option pops up. Running it from Terminal has the same problem.

**Comment by lordloki** [comment] 2021-12-07 17:23
Could you test this procedure?
![image](https://user-images.githubusercontent.com/1015605/145076528-8c8aa762-facd-4c64-856c-dc77d4c4301d.png)

**Comment by lordloki** [comment] 2021-12-08 13:08
Could you test with this build?:
https://mega.nz/file/15Mk0LJB#KHUpP9lwQEXiEVYnXY65ut3z79hJttCynP-9Pl3-pis

**Comment by lordloki** [comment] 2021-12-09 19:47
It seems that it is working from several discord reports. Then I close the issue.

If you continue having issues launching UPBGe in Mac, please feel free to open this issue again.

Thanks for the feedback.

**Comment by keeganstothert** [comment] 2021-12-10 21:07
Still not resolved for me on the latest build. I'm using m1 max macbook pro and I tried it with both aarch and x86 binaries

**Comment by keeganstothert** [comment] 2021-12-10 21:09
The x86 build works through rosetta but the aarch arm build fails with the same issue

**Comment by lordloki** [comment] 2021-12-13 09:46
@keeganstothert A new arm build has been uploaded. Could you test it? Thanks.

**Comment by keeganstothert** [comment] 2021-12-15 04:58
@lordloki unfortunately the issue is the same.

![Screen Shot 2021-12-14 at 8 58 02 PM](https://user-images.githubusercontent.com/3612936/146125994-6d1f3eb1-931d-4549-b160-da90581c2a48.png)

**Comment by lordloki** [comment] 2021-12-15 07:56
@keeganstothert only to be sure. The builds haven't official signature then it is necessary:
![image](https://user-images.githubusercontent.com/1015605/146145824-5ed1e711-3634-44f2-b9d9-a9ac332ba608.png)
2. Click in the padlock icon (lower-left) to can make changes
3. Select Allow downloader app from: Anywhere
![image](https://user-images.githubusercontent.com/1015605/146146056-7f44ef93-f954-4ccf-9c53-95a291d824b4.png)
Then you should try to open the file again

**Comment by keeganstothert** [comment] 2021-12-28 01:08
@lordloki the screenshots you posted show a very old version of macos. Gatekeeper no longer has an "Anywhere" option instead it will show
<img width="570" alt="Screen Shot 2021-12-27 at 5 05 11 PM" src="https://user-images.githubusercontent.com/3612936/147516873-e9ba4fea-e2e3-43cb-b042-cce50a4ca253.png">
 
in anycase, that option does not appear which I've seen before and seems indicate the build is not working for reasons other than gatekeeper

**Comment by fumangy** [comment] 2022-02-27 00:24
> Hello, The app still not working on ARM-based MacBook:
> 
> * Apple Silicon M1 Pro
> * macOS Monterey v12.2.1
> * UPBGE ARM-based
> 
> I tried to launch the app directly, and with a terminal in both cases I have the message "UPBGE is damaged and can’t be opened". And there is nothing in the Gatekeeper.
 
I made  build of UPBGE 3.2.0 Alpha for Mac. The great novelty of this latest build is compatible with Metal. Best regards. 

Discord
(https://discord.com/channels/481036814539292672/623603265875214349/946731415641411594)

Link donwland
(https://mega.nz/file/4ng32QLR#NinhDpyfVlgZP8LMdYoHT0on-5XmZtVkQXbKkBetG1U)

**Comment by jferdelyi** [comment] 2022-02-27 08:16
It's working ! Thank you.

**Comment by lordloki** [comment] 2022-05-24 20:09
Here you have the link for the Alpha builds including the Mac one https://mega.nz/fm/ZtcDzYYA. 
Currently, the mac alpha build are starting to use Metal library instead of OpenGL.

**Comment by lordloki** [comment] 2022-06-26 22:29
I just include a note in the webpage pointing to wiki page exposing how to fix this issue.
![image](https://user-images.githubusercontent.com/1015605/175836133-7e92f238-6da0-40ef-8d1d-a24c0b22a358.png)

The wiki page is https://github.com/UPBGE/upbge/wiki/MacOS-remove-UPBGE-damaged-comment

I close this issue. Thanks for all the support & feedback.

**Closed by lordloki** 2022-06-26 22:29 UTC
Labels: bug, 0.3+, macOS

**Comment by Michael-Z-Freeman** [comment] 2023-02-10 11:31
On my Apple M1 Ventura I had to restart my system after the xattr command before UPBGE eventually restarted. I’m sure the devs have their reasons for not signing but this is first app out of hundred that requires that command. For example Meshlab and of course mainstream Blender itself don’t require this. But cheers for an M1 build !

**Comment by TriVoxel** [comment] 2023-02-14 02:37
@Michael-Z-Freeman Hey there, I'm probably the one who built the M1 version you're using. We actually did _try_ to sign it, but it didn't seem to work. So, we just decided not to since Apple charges money for you to compile and distribute software for Apple computers and it didn't even work. I spent probably a good week or so trying to get the M1 version to work properly when we distributed it. Finally, we kinda just gave up on that because this seems to work okay. Despie my best efforts, it would run flawlessly on my Mac, I'd test it on another one of my Macs, all good. I sealed it up in a DMG with the nice background art and Applications folder link, and nobody could use it lol. Sorry for the inconvenience. Hopefully this gets sorted out one day.

**Comment by Clemens865** [comment] 2023-03-10 07:54
Tried to install the UPGE on my Mac Pro M1, Ventura 13.2.1
Tried to open it through the terminal with the command: xattr -cr UPBGE-0.30-macOS-arm64.dmg
However it comes up with the following message: xattr: No such file: UPBGE-0.30-macOS-arm64.dmg
Double checked the file, and the name is identical. File is in the download folder. 

Any help would be appreciated.
