### ISSUE TITLE
What are the Plans of integrating EEvEE next in to UPBGE?

### ISSUE THREAD

**Issue by eliecer696** [UPBGE/upbge#1813] opened 2023-06-28 11:38 UTC
i was looking in to EEVEE next and i was wandering is there any future plans of implementing the new EEVEE next in upbge

**Comment by youle31** [comment] 2023-06-30 15:33
it is already available normally. You just need to enable it in user preferneces, and choose it as render engine, then press P to start bge runtime (as it is not a bug report, i close this thread)

**Closed by youle31** 2023-06-30 15:33 UTC

**Comment by eliecer696** [comment] 2023-06-30 15:35
i used it in upbge 0.33 and it crashes when i run it

**Comment by youle31** [comment] 2023-06-30 15:36
and in 3.6 beta?

**Comment by eliecer696** [comment] 2023-06-30 16:13
in the 3.6 betta the option for eevee next is not available am using windows 10
![image](https://github.com/UPBGE/upbge/assets/4975856/c7869b87-ac9f-4d44-95c2-435fe0ad0590)

**Comment by eliecer696** [comment] 2023-07-01 00:33
> and in 3.6 beta?

it's only on available on the 3.6 alpha but not on the beta, also other components such as game engine physics panels and render property's are gone from the property panel this appears to be a separate bug of its own should i report it in a separate thread?
