### ISSUE TITLE
Crash 0.2.5 when using Geometry Instancing

### ISSUE THREAD

**Issue by BlenderDoc** [UPBGE/upbge#1208] opened 2020-05-10 13:45 UTC
Hi. As it said. I copy the Standard Cube (alt+d or converted Particle System) 1000 times, and enable the Geometry Instancing Option. UpBGE crashes almost immediately.

**Comment by lordloki** [comment] 2020-05-10 16:27
I have copied (alt + d) 5000 times and it doesn't crash.
![image](https://user-images.githubusercontent.com/1015605/81504828-c5b27c00-92eb-11ea-8100-0ee5008f3f0c.png)
Could you pass us your blend before to activate Geometry instance option?

**Comment by BlenderDoc** [comment] 2020-05-10 17:49
Thank you for investigation. Hm, maybe i'm doing something wrong? Sometimes, it takes a couple of tries to crash it. But finally it will, in my case. Mostly after loading into a fresh started Blender. But often also after converting a Particle System. (Gras; Rocks etc.)

I always delete the whole Directory when using a new Build. I don't unpack the Files into the old.
But i currently noticed, i get an Error in the Console:
Error: coulding import the module 'module'
ModuleNotFoundError: No module named 'module'

Here is a blend.
[Crash Geometry Instances.zip](https://github.com/UPBGE/upbge/files/4606322/Crash.Geometry.Instances.zip)

My System:
Win10 64
Ryzen 5 3600X 6 Core CPU
Radeon RX 590

**Comment by BlenderDoc** [comment] 2020-05-10 23:00
Hmm, i noticed something. I used this Testing File: (converted from Particle System)
[Crash Geometrie Instancing (Studie converted).zip](https://github.com/UPBGE/upbge/files/4606882/Crash.Geometrie.Instancing.Studie.converted.zip)

Sometimes it crashes immediately. Sometimes it take 20 or more tries. And i got different System Load. Almost exactly these two states.
![GeoInst_2](https://user-images.githubusercontent.com/32316134/81512645-6885ed00-9322-11ea-8a1f-1d5cb690a247.jpg)
I can't see what the Values are when it crashes.

**Comment by lordloki** [comment] 2020-05-11 05:12
Strange. I just trying to force the geometry instancing and I can't it to crash
![image](https://user-images.githubusercontent.com/1015605/81525935-8705db80-9356-11ea-9c0b-30ed4c50bd29.png)
I did a fresh install, I start the game around 300 times, increasing the cubes until 30000 and it worked well. Maybe is it related to AMD graphics card?

**Comment by BluePrintRandom** [comment] 2020-05-11 06:30
VRAM limit?

**Comment by youle31** [comment] 2020-05-11 08:31
I can't reproduce the crash with this test file: Crash Geometrie Instancing (Studie converted).zip (8700k, gtx 1080)

**Comment by BlenderDoc** [comment] 2020-05-11 16:29
I have started a Challenge. Let's see if i am the only one who crash this. :)
https://blenderartists.org/t/upbge-who-can-crash-this-file/1227306

**Comment by lordloki** [comment] 2020-05-11 16:53
Doc, Could you test the following?
Could you lower 15% the graphics card power using a program as Wattman?

I read in the reddit that that card has issues with a lot games and this helps to solve it

**Comment by BlenderDoc** [comment] 2020-05-11 18:23
Hm, don't notice Issues in Games i've played since i have this Card. Normally, i don't play around that this Features. Anyway, i lower the Power. But without sucess. It's still crashing.

Who know where the Problem is? Maybee with the next Driver Update comes more Light in the Dark, i'll see.
Thank You.

**Comment by youle31** [comment] 2020-05-12 15:19
[debug_logs.zip](https://github.com/UPBGE/upbge/files/4616501/debug_logs.zip)

**Comment by lordloki** [comment] 2020-05-12 17:51
according to the files there is 2 performance issues:
GL API performance: glDrawElements uses element index type 'GL_UNSIGNED_BYTE' that is not optimal for the current hardware configuration; consider using 'GL_UNSIGNED_SHORT' instead
GL API performance: glDrawElementsInstanced uses input attribute 'VERTEX_ATTRIB[2]' with offset '71' that is not optimally aligned; consider aligning on a 4-byte boundary

I was doing several tests (changing things) but without success (i have a lack of OpenLG knowledge).
I will investigate a bit more

**Comment by youle31** [comment] 2020-05-14 08:16
@BlenderDoc : hi, is upbge still crashing with this build? : https://drive.google.com/file/d/1TD20H-7U9k9nqu3ChudWhPDky0IeqSEX/view?usp=sharing

I applied this patch: 

https://drive.google.com/file/d/1sDvS06CTBUtviZ4DiZdu4RDxsqJPN5Zl/view?usp=sharing

Notes:
- I compiled without the addons (the 2.79 folder can be replaced with the one from lordloki build)
- If with luck it solves the issue for BlenderDoc, i think this patch shouldn't be applied to the main 0.2.5 master because of potential bad side effects if we replace uint with ushort.
Instead, when lordloki will publish 0.2.5a in some time, another build with this patch could be done for the ones who have drivers issue with uint.

**Comment by BlenderDoc** [comment] 2020-05-15 02:59
Thank you. I'm so sorry but it doesn't help. It still crashes. I am grateful for all the effort, but please don't waste your time. I'm pretty sure it's just my system. Maybe my graphics card has a gremlin, or something.

But i made some logs, like above.
Mostley it crashes imidietly after loading the File for the first time. The second try needed 7 tries to crash.
[debug_logs_1st.zip](https://github.com/UPBGE/upbge/files/4631994/debug_logs_1st.zip)
[debug_logs_2nd.zip](https://github.com/UPBGE/upbge/files/4631995/debug_logs_2nd.zip)

**Comment by youle31** [comment] 2020-05-15 03:49
Well, ok... I tried to replace GL_UNSIGNED_INT with GL_UNSIGNED_SHORT in some parts of the code, and as my graphic card didn't complain, i posted this build but it seems it doesn't fix anything.
We could try other things, but without having hardware to reproduce the crash i fear that it would require many tests, that we'd need to upload many builds......

As it isn't really doable without having the hardware to check, i'll close this issue even if the problem is not solved.

Note: I saw that there were still drivers updates for RX 590 cards (23 april 2020 for last driver)

I'll added the label connot be fixed, if someday someone can reproduce the issue and want to investigate in closed issues.

**Closed by youle31** 2020-05-15 03:49 UTC
Labels: cannot be fixed
