### ISSUE TITLE
multiprocessing not found warning + crash with python controller module script

### ISSUE THREAD

**Issue by BerglerAndi** [UPBGE/upbge#1435] opened 2021-03-15 16:27 UTC
My exported game doesn't work anymore. There is a multiprocessing error. I worked with 0.3.0 02.03.2021 and 12.03.2021 for two weeks without any error.

Now the exported game doesn't work:
"Unable to find the python binary, the multiprocessing module may not be functional!"

**Comment by BerglerAndi** [comment] 2021-03-15 16:46
I saw that, a version a few day ago throws the same error, but the game starts. What can i do?
Downgrading to 0.03 with 2.91 or 2.83 helps, but i'd like to avoid to downgrade the game. There are missing some features like max slope.

**Comment by lordloki** [comment] 2021-03-15 18:06
Hi, 
I just tested with current windows and it worked.
![image](https://user-images.githubusercontent.com/1015605/111199872-713df400-85c1-11eb-96a4-d9a13e0efb32.png)
Could you say me which OS do you use?
Could you paste here a screenshot of the console?

**Comment by BerglerAndi** [comment] 2021-03-15 19:42
Hey,
the console is just viewing a few milliseconds. I filmed that and saw just this:
"Unable to find the python binary, the multiprocessing module may not be functional!"

I use Windows64.

That game runs in upbge fine, the error just occures when i export the game.

**Comment by BerglerAndi** [comment] 2021-03-15 22:21
I found the reason for the error:
It was a link to a not existing python script in a Controller inside the logic brick editor.
![grafik](https://user-images.githubusercontent.com/58920393/111228795-1c13d980-85e5-11eb-9ecf-2883853121bf.png)

omg, what a stupid mistake and waste of time..

**Comment by BerglerAndi** [comment] 2021-03-15 22:37
“Unable to find the python binary, the multiprocessing module may not be functional!”
The error is still thrown..

..It hasnt to do anything with the crash, obviously

**Comment by youle31** [comment] 2021-03-16 02:41
Could you provide the test file to help us to solce the crash?

**Comment by BerglerAndi** [comment] 2021-03-16 20:38
Sure
[test.zip](https://github.com/UPBGE/upbge/files/6152085/test.zip)

Try this with a new blender-file:
![grafik](https://user-images.githubusercontent.com/58920393/111376563-e54ec980-869f-11eb-8b0a-45a1f8308fc4.png)

**Comment by youle31** [comment] 2021-03-17 00:06
I can't reproduce the crash, neither with your file, neither with a new file with same setup. I'll close the report for now, and if the bug appears in another file and that i can reproduce it, i'll try to fix. Thanks

**Comment by youle31** [comment] 2021-03-19 03:23
I can reproduce the crash for an exported runtime only

**Comment by BerglerAndi** [comment] 2021-03-19 09:30
Hey youle,
that's what I'm talking about, when I write exported game. Sorry for that. I'm have learn a lot..

By the way. The error multiprocessing has not to do anything with the script crash. The runtime throws the multiprocessing error and starts, if the script error is fixed.

**Comment by youle31** [comment] 2021-03-19 13:03
Thanks for the report, I pushed a fix for the crash. We'll see later for warnings at blenderplayer start (concerning multiprocessing, and when we don't copy scripts folder in exported game folder)

**Closed by youle31** 2021-03-19 13:03 UTC
Labels: 0.3, bug
