### ISSUE TITLE
[Request] group object: python components possible?

### ISSUE THREAD

**Issue by MoritzBrueckner** [UPBGE/upbge#440] opened 2017-03-24 16:31 UTC
Hello,

I wonder if it's possible to assign components to groups. This would be great because you could add changeable parameters for linked groups. 

**As an example:** Imagine you have a camp fire or a lamp that you have linked from another file as a group object. If you want that lamp to have two states without changing them manually ingame (in this case _on_ and _off_), it would be great to have this option in an user interface like python components (or better: not "like", why not components themself?). I wanted to try if this is already possible, but unfortunately it didn't work as expected.

Because you can't edit the group object manually, I tried to import the python file with the component class in it into another python file and then add it to the components by using `owner.groupObject.components.append(filename.Classname)`

As I mentioned before, this didn't work. I get the following error:
`TypeError: CList.append(i): CValueList, could [not? I think there is a word missing] convert python value to a game engine property`

So, did I make a mistake or is this not possible? If it isn't possible, please see this as a feature request :) I know, you have a lot of work to do which is way more important, so see this as low priority.

Thank you 👍

**Comment by panzergame** [comment] 2017-03-24 17:27
For the moment you could add python components to a group instance but not the group itself, so for the case of the lamp, you need to import a group instance and not the objects.

**Comment by Momel15** [comment] 2017-03-24 18:35
The problem is that you would have to do that manually in the main file, or am I wrong? You would have to copy the group instances to prevent to manually add components to all of them. Adding them with `Shift + A` as a group instance wouldn't be enough, the group instance would have no components and no logic bricks as well.

**Comment by pqftgs** [comment] 2017-03-26 07:17
@Momel15 you are correct.  It's kinda painful with lots of assets.

Among my vast hoard of silly hacks that never see daylight was a patch that let you toggle a property to be editable from group instances.  But now I think doing it with components is a better idea.

Proposal: All components contained within a group should appear on instances.  From there you can edit its values, but not delete the component.  Maybe have a toggle button for certain components that you don't want to expose to designers.

Thoughts?  Anyone already working on this?

**Comment by Momel15** [comment] 2017-03-26 08:44
This is a great idea :) A very big advantage of it is that you wouldn't need to create a component for the group which communicates with the components in the group because you can directly set the values.

**Comment by lordloki** [comment] 2020-05-03 12:51
Closing as new tracker rules but open and feature for later tags added.

**Closed by lordloki** 2020-05-03 12:51 UTC
Labels: Open, feature request for later
